# Generated by Django 6.0.6 on 2026-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionconfig",
            name="band_multiplier",
            field=models.FloatField(
                default=1.0,
                help_text="Eligibility band width multiplier applied to the ± variance around the prediction. 1.0 = default width. 1.5 = 50% wider (more Borderline, fewer Unlikely). 0.7 = narrower (tighter Likely/Unlikely split).",
            ),
        ),
    ]
