# Generated by Django 5.2.15 on 2026-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_alter_predictionconfig_band_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionconfig",
            name="band_multiplier",
            field=models.FloatField(
                default=1.5,
                help_text="Eligibility band width multiplier applied to the ± variance around the prediction. 1.0 = raw recent volatility. 1.5 (default) = 50% wider (more Borderline, fewer Unlikely). 0.7 = narrower (tighter Likely/Unlikely split).",
            ),
        ),
        migrations.AlterField(
            model_name="predictionconfig",
            name="rising_floor_multiplier",
            field=models.FloatField(
                default=0.0,
                help_text="Rising courses: fraction of last year's gain added on top of the latest cutoff. 0.0 (default, best in 2024/2025 backtest) holds at the latest cutoff; 0.50 adds 50% of the last gain. Range: 0.0 (no uplift) – 2.0 (double the gain).",
            ),
        ),
    ]
