# Generated by Django 5.2.15 on 2026-10-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0003_backtest_2025_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionconfig",
            name="cohort_shift",
            field=models.FloatField(
                default=0.0,
                help_text="Points added to every prediction (and floor) for the coming year, for a cohort-wide move history can't see. Set it when the new KCSE results are out: positive if more candidates scored C+ and above than last year (cutoffs rise), negative if fewer. Past moves: 2023 −0.5, 2024 −0.8, 2025 +1.0. Range about −2 to +2; 0.0 = no adjustment.",
            ),
        ),
    ]
