# Generated by Django 6.0.6 on 2026-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_checkout_id_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, help_text="Price in KES (0 = free)"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to make this feature free for everyone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Feature",
                "verbose_name_plural": "Payment Features",
            },
        ),
    ]
