# Generated by Django 6.0.6 on 2026-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_seed_payment_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mpesa_code",
            field=models.CharField(
                blank=True,
                help_text="User-submitted M-Pesa transaction code for manual verification",
                max_length=20,
            ),
        ),
    ]
