# Generated by Django 6.0.6 on 2026-06-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_add_mpesa_code_to_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentExemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All features"),
                            ("view_cluster_points", "View Cluster Points"),
                            ("view_eligible_courses", "View Eligible Courses"),
                            ("premium_career_report", "Premium Career Report"),
                            ("advanced_analysis", "Advanced Career Analysis"),
                        ],
                        help_text="Leave blank to exempt from ALL payment-gated features.",
                        max_length=50,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Reason for exemption (internal use only).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_exemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_exemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Exemption",
                "verbose_name_plural": "Payment Exemptions",
                "unique_together": {("user", "feature")},
            },
        ),
    ]
