# Generated by Django 6.0.6 on 2026-06-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_exemption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="feature",
            field=models.CharField(
                choices=[
                    ("view_cluster_points", "View Cluster Points"),
                    ("view_eligible_courses", "View Eligible Courses"),
                    ("premium_career_report", "Premium Career Report"),
                    ("advanced_analysis", "Advanced Career Analysis"),
                    ("ai_chat_access", "AI Chat Top-Up"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentexemption",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "All features"),
                    ("view_cluster_points", "View Cluster Points"),
                    ("view_eligible_courses", "View Eligible Courses"),
                    ("premium_career_report", "Premium Career Report"),
                    ("advanced_analysis", "Advanced Career Analysis"),
                    ("ai_chat_access", "AI Chat Top-Up"),
                ],
                help_text="Leave blank to exempt from ALL payment-gated features.",
                max_length=50,
            ),
        ),
    ]
