# Generated by Django 6.0.6 on 2026-06-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0010_mentorprofile_mentorship__is_appr_095597_idx_and_more"),
        ("payments", "0009_payment_payments_pa_user_id_407fec_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mentorship_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_record",
                to="mentorship.mentorshipsession",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="feature",
            field=models.CharField(
                choices=[
                    ("view_cluster_points", "View Cluster Points"),
                    ("view_eligible_courses", "View Eligible Courses"),
                    ("premium_career_report", "Premium Career Report"),
                    ("advanced_analysis", "Advanced Career Analysis"),
                    ("ai_chat_access", "AI Chat Top-Up"),
                    ("mentorship_booking", "Mentorship Booking"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentexemption",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "All features"),
                    ("view_cluster_points", "View Cluster Points"),
                    ("view_eligible_courses", "View Eligible Courses"),
                    ("premium_career_report", "Premium Career Report"),
                    ("advanced_analysis", "Advanced Career Analysis"),
                    ("ai_chat_access", "AI Chat Top-Up"),
                    ("mentorship_booking", "Mentorship Booking"),
                ],
                help_text="Leave blank to exempt from ALL payment-gated features.",
                max_length=50,
            ),
        ),
    ]
