# Generated by Django 5.2.15 on 2026-09-28 19:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_schedule_check_pending_payments"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                django.db.models.functions.text.Upper("mpesa_ref"),
                name="payments_txn_mpesa_ref_upper",
            ),
        ),
    ]
