# Generated by Django 5.2.15 on 2026-10-01 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0014_db_integrity_hardening"),
        ("payments", "0012_db_index_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="payment_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "completed", "failed", "refunded"])
                ),
                name="payment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="transaction_amount_non_negative",
            ),
        ),
    ]
