"""
Generates normalized TVET data for the seed command.
Output: tvet_seed_data.json
"""
import json, re
from collections import defaultdict

with open('tvet_raw_data.json', encoding='utf-8') as f:
    raw = json.load(f)

# ─────────────────────────────────────────────────────────────────────────────
# 1. CANONICAL PROGRAMME MAP  (raw name → canonical name)
# ─────────────────────────────────────────────────────────────────────────────
CANONICAL_MAP = {
    # BUSINESS & COMMERCE
    'Diploma In Accountancy': 'Diploma in Accountancy',
    'Diploma In  Accountancy': 'Diploma in Accountancy',
    'Diploma In Accountant Technician': 'Diploma in Accountancy',
    'Diploma In Accountants Technicians': 'Diploma in Accountancy',
    'Diploma In  Accountants Technicians Diploma': 'Diploma in Accountancy',
    'Diploma In Accounting': 'Diploma in Accountancy',
    'Diploma In Accounting & Finance': 'Diploma in Accountancy',
    'Diploma In Accounting Technician': 'Diploma in Accountancy',
    'Diploma In Accounting Technicians': 'Diploma in Accountancy',
    'Diploma In Banking': 'Diploma in Banking & Finance',
    'Diploma In Banking & Finance': 'Diploma in Banking & Finance',
    'Diploma In Banking And Finance': 'Diploma in Banking & Finance',
    'Diploma In Business Administration': 'Diploma in Business Management',
    'Diploma In Business Administration/Management': 'Diploma in Business Management',
    'Diploma In Business Management': 'Diploma in Business Management',
    'Diploma In Sale And Marketing': 'Diploma in Sales & Marketing',
    'Diploma In Sales & Marketing': 'Diploma in Sales & Marketing',
    'Diploma In Sales And Marketing': 'Diploma in Sales & Marketing',
    'Diploma In Supply Chain  Management': 'Diploma in Supply Chain Management',
    'Diploma In Supply Chain Management': 'Diploma in Supply Chain Management',
    'Diploma In In Supply Chain Management': 'Diploma in Supply Chain Management',
    'Diploma In Supliles Chain Management': 'Diploma in Supply Chain Management',
    'Diploma In Supplies And Chain Management': 'Diploma in Supply Chain Management',
    'Diploma In Supplies Chain Management': 'Diploma in Supply Chain Management',
    'Diploma In Supplies Management': 'Diploma in Supply Chain Management',
    'Diploma In Procurement And Materials Management': 'Diploma in Procurement & Supply Chain Management',
    'Diploma In Procurement And Supply Chain Management': 'Diploma in Procurement & Supply Chain Management',
    'Diploma In Purchasing And Supplies Chain Management': 'Diploma in Procurement & Supply Chain Management',
    'Diploma In Purchasing And Supplies Management': 'Diploma in Procurement & Supply Chain Management',
    'Diploma In Human Resource': 'Diploma in Human Resource Management',
    'Diploma In Human Resource Management': 'Diploma in Human Resource Management',
    'Diploma In Co-Operative Management': 'Diploma in Co-operative Management',
    'Diploma In Cooperative Development': 'Diploma in Co-operative Management',
    'Diploma In Cooperative Management': 'Diploma in Co-operative Management',
    'Diploma In Secretarial Studies': 'Diploma in Secretarial Studies',
    'Diploma In Computerized Secretarial Studies': 'Diploma in Secretarial Studies',
    'Diploma In Secretarial Studies (Computerised)': 'Diploma in Secretarial Studies',
    'Diploma In Secretarial Studies And Office Management': 'Diploma in Secretarial Studies',
    'Diploma In Credit Management': 'Diploma in Credit Management',
    'Diploma In Tax Administration': 'Diploma in Tax Administration',
    'Diploma In Customs Administration': 'Diploma in Customs Administration',
    'Diploma In Entrepreneurship': 'Diploma in Entrepreneurship',
    'Diploma In Entrepreneurship Development': 'Diploma in Entrepreneurship',
    'Diploma In Entrepreneurship Education': 'Diploma in Entrepreneurship',
    'Diploma In Project Management': 'Diploma in Project Management',
    'Diploma In Corporate Governance': 'Diploma in Corporate Governance',
    'Diploma In Public Relations': 'Diploma in Public Relations',
    'Diploma In Public Relations And Creative Advertising': 'Diploma in Public Relations',
    'Diploma In Office Administration': 'Diploma in Office Administration',
    'Diploma In Clerical Operations': 'Diploma in Office Administration',
    'Diploma In Liberal Studies And Management': 'Diploma in Liberal Studies & Management',
    'Diploma In Applied Statistics': 'Diploma in Applied Statistics',
    'Diploma In Kenya School Of Revenue Administration': 'Diploma in Tax Administration',
    # COMPUTING & ICT
    'Diploma In Information Communication Technology': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information Communication  Technology': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information And Communication Technology (Ict)': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information Communication Technician': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information Communication Technology (Ict)': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information Communication Technology(Ict)': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information & Communication Technology': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Certified Information Communication Technology': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Information Technology': 'Diploma in Information Communication Technology (ICT)',
    'Diploma In Computer Science': 'Diploma in Computer Science',
    'Diploma In Computer Studies': 'Diploma in Computer Science',
    'Diploma In Computer Programming': 'Diploma in Computer Science',
    'Diploma In Computer Systems': 'Diploma in Computer Science',
    'Diploma In Software Development': 'Diploma in Software Development',
    'Diploma In Software Design And Programming': 'Diploma in Software Development',
    'Diploma In Data Management And Analytics': 'Diploma in Data Management & Analytics',
    'Diploma In Network And Systems Admministration': 'Diploma in Network & Systems Administration',
    'Diploma In Graphic Design': 'Diploma in Graphic Design',
    'Diploma In Graphic And Web Design': 'Diploma in Graphic Design',
    'Diploma In Animation And Graphics Design': 'Diploma in Animation & Graphics Design',
    'Diploma In Information Science': 'Diploma in Information Science',
    'Diploma In Information Science Level Six(Tvet-Cdacc)': 'Diploma in Information Science',
    'Diploma In Information Studies': 'Diploma in Information Science',
    # ENGINEERING & TECHNOLOGY
    'Diploma In Electrical & Electronic Engineering (Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronic Engineering (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronic Engineering (Telecommunication Option)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical & Electronic Engineering (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical & Electronic Engineering (Telecommunications)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical & Electronic Engineering(Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Engineering': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Engineering (Control & Instrumentation)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical & Electronics Engineering (Electronics Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Engineering (Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Engineering (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Engineering (Telecommunication Option)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical & Electronics Engineering (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical & Electronics Level Six(Tivet)-Cdacc': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Technology': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical & Electronics Technology (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical (Instrumentation)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical And Electronic Technology (Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics (Instrumentation & Control)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical And Electronics (Instrumentation)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical And Electronics (Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical And Electronics Engineering': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics Engineering (Instrumentation & Control)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical And Electronics Engineering (Instrumentation Option)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical And Electronics Engineering (Instrumentation)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    'Diploma In Electrical And Electronics Engineering (Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics Engineering (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics Engineering(Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics Technology (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical And Electronics Technology (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical Electronics (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical Electronics (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical Engineering': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical Engineering (Power Option)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical Engineering (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical Engineering (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical Engineering(Electronics )': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical Engineering(Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electrical/ Electronics Technology (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical/Electronic Engineering (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electronics': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Electronics Engineering': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Elctrical Engineering (Power)': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Elctrical Engineering (Telecommunication)': 'Diploma in Electrical & Electronics Engineering (Telecommunication)',
    'Diploma In Electrical & Electronic Engineering(Power Option) -Knec': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Technology In Electrical Power Engineering': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Technology In Electronic Engineering': 'Diploma in Electrical & Electronics Engineering (Power)',
    'Diploma In Mechanical Engineering': 'Diploma in Mechanical Engineering (Plant)',
    'Diploma In Mechanical Engineering ( Plant)': 'Diploma in Mechanical Engineering (Plant)',
    'Diploma In Mechanical Engineering (Automotive Engineering Option)': 'Diploma in Mechanical Engineering (Automotive)',
    'Diploma In Mechanical Engineering (Automotive Option)': 'Diploma in Mechanical Engineering (Automotive)',
    'Diploma In Mechanical Engineering (Automotive)': 'Diploma in Mechanical Engineering (Automotive)',
    'Diploma In Mechanical Engineering (Plant Option)': 'Diploma in Mechanical Engineering (Plant)',
    'Diploma In Mechanical Engineering (Plant)': 'Diploma in Mechanical Engineering (Plant)',
    'Diploma In Mechanical Engineering (Production Option)': 'Diploma in Mechanical Engineering (Production)',
    'Diploma In Mechanical Engineering (Production)': 'Diploma in Mechanical Engineering (Production)',
    'Diploma In Mechanical Engineering(Production Option)': 'Diploma in Mechanical Engineering (Production)',
    'Diploma In Mechanical Production Technician': 'Diploma in Mechanical Engineering (Production)',
    'Diploma In Mechanical Production Technician Level 6': 'Diploma in Mechanical Engineering (Production)',
    'Diploma In Mechatronic Engineering': 'Diploma in Mechatronics',
    'Diploma In Mechatronic Technician': 'Diploma in Mechatronics',
    'Diploma In Mechatronic Technology': 'Diploma in Mechatronics',
    'Diploma In Mechatronics': 'Diploma in Mechatronics',
    'Diploma In Civil Engineering': 'Diploma in Civil Engineering',
    'Diploma In Civil Engineering Mod 1': 'Diploma in Civil Engineering',
    'Diploma In Civil Engineering Technology': 'Diploma in Civil Engineering',
    'Diploma In Building': 'Diploma in Building & Construction Technology',
    'Diploma In Building &  Construction Technology': 'Diploma in Building & Construction Technology',
    'Diploma In Building & Construction': 'Diploma in Building & Construction Technology',
    'Diploma In Building And Civil Engineering': 'Diploma in Building & Construction Technology',
    'Diploma In Building And Construction': 'Diploma in Building & Construction Technology',
    'Diploma In Building Construction': 'Diploma in Building & Construction Technology',
    'Diploma In Building Construction Technology': 'Diploma in Building & Construction Technology',
    'Diploma In Building Engineering Technology': 'Diploma in Building & Construction Technology',
    'Diploma In Building Technician (Cdacc)': 'Diploma in Building & Construction Technology',
    'Diploma In Building Technology': 'Diploma in Building & Construction Technology',
    'Diploma In Automotive Engineering': 'Diploma in Automotive Engineering',
    'Diploma In Automotive Technology': 'Diploma in Automotive Engineering',
    'Diploma In Motor Vehicle Mechanics': 'Diploma in Automotive Engineering',
    'Diploma In Welding And Fabrication': 'Diploma in Welding & Fabrication',
    'Diploma In Welding And Fabrication -(Cbet Level 6)': 'Diploma in Welding & Fabrication',
    'Diploma In Chemical Engineering': 'Diploma in Chemical Engineering',
    'Diploma In Chemical Engineering Technology Level Six( Tvet-Cdacc)': 'Diploma in Chemical Engineering',
    'Diploma In Refrigeration & Air Conditioning': 'Diploma in Refrigeration & Air Conditioning',
    'Diploma In Refrigeration And Air Conditioning': 'Diploma in Refrigeration & Air Conditioning',
    'Diploma In Marine Engineering': 'Diploma in Marine Engineering',
    'Diploma In Telecommunication Engineering': 'Diploma in Telecommunication Engineering',
    'Diploma In Construction Management': 'Diploma in Construction Management',
    'Diploma In Construction Plant': 'Diploma in Construction Plant Engineering',
    'Diploma In Construction Plant Engineering': 'Diploma in Construction Plant Engineering',
    'Diploma In Highways Engineering': 'Diploma in Civil Engineering (Roads & Highways)',
    'Diploma In Road Construction': 'Diploma in Civil Engineering (Roads & Highways)',
    'Diploma In Plant And Services Engineering': 'Diploma in Plant & Services Engineering',
    'Diploma In Agricultural Engineering': 'Diploma in Agricultural Engineering',
    'Diploma In Agriculture Engineering': 'Diploma in Agricultural Engineering',
    'Diploma In Agricultural Irrigation And Drainage Engineering': 'Diploma in Irrigation & Drainage Engineering',
    'Diploma In Irrigation And Drainage Engineering': 'Diploma in Irrigation & Drainage Engineering',
    'Diploma In Water Engineering': 'Diploma in Water Engineering & Technology',
    'Diploma In Water Engineering (Cbet Level 6)': 'Diploma in Water Engineering & Technology',
    'Diploma In Water Resources Management And Technology': 'Diploma in Water Engineering & Technology',
    'Diploma In Water Technology': 'Diploma in Water Engineering & Technology',
    'Diploma In Water Technology (Water Supply Option)': 'Diploma in Water Engineering & Technology',
    'Diploma In Aeronautical Engineering (Airframes And Engines)': 'Diploma in Aeronautical Engineering (Airframes & Engines)',
    'Diploma In Aeronautical Engineering (Avionics)': 'Diploma in Aeronautical Engineering (Avionics)',
    'Diploma In Technology (Aeronautical Engineering)': 'Diploma in Aeronautical Engineering (Airframes & Engines)',
    'Diploma In Printing Technology': 'Diploma in Printing Technology',
    'Diploma In Media Technology': 'Diploma in Media Technology',
    'Diploma In Petroleum And Geoscience': 'Diploma in Petroleum & Geoscience',
    'Diploma In Petroleum Management': 'Diploma in Petroleum Management',
    # HEALTH SCIENCES
    'Diploma In Medical Laboratory Science': 'Diploma in Medical Laboratory Sciences',
    'Diploma In Medical Laboratory Sciences': 'Diploma in Medical Laboratory Sciences',
    'Diploma In Medical Laboratory Technology': 'Diploma in Medical Laboratory Sciences',
    'Diploma In Community Health': 'Diploma in Community Health',
    'Diploma In Community Health & Hiv Management': 'Diploma in Community Health',
    'Diploma In Community Health And Development': 'Diploma in Community Health',
    'Diploma In Community Health And Nutrition': 'Diploma in Community Health',
    'Diploma In Community Health Level 6 (Cbet)': 'Diploma in Community Health',
    'Diploma In Nutrition & Dietetic Management': 'Diploma in Nutrition & Dietetics',
    'Diploma In Nutrition & Dietetics': 'Diploma in Nutrition & Dietetics',
    'Diploma In Nutrition And Diet Management': 'Diploma in Nutrition & Dietetics',
    'Diploma In Nutrition And Dietetics': 'Diploma in Nutrition & Dietetics',
    'Diploma In Food Nutrition & Dietetics': 'Diploma in Nutrition & Dietetics',
    'Diploma In Dietetic Management': 'Diploma in Nutrition & Dietetics',
    'Diploma In Dietetics Management': 'Diploma in Nutrition & Dietetics',
    'Diploma In Enviromental Health Sciences': 'Diploma in Environmental Health Sciences',
    'Diploma In Medical Engineering': 'Diploma in Medical Engineering',
    'Diploma In Technology Medical Engineering': 'Diploma in Medical Engineering',
    'Diploma In Pharmaceutical Technology': 'Diploma in Pharmaceutical Technology',
    'Diploma In Health Records': 'Diploma in Health Records & Information Technology',
    'Diploma In Health Records And Information Technology': 'Diploma in Health Records & Information Technology',
    # AGRICULTURE
    'Diploma In General Agriculture': 'Diploma in General Agriculture',
    'Diploma In  General Agriculture': 'Diploma in General Agriculture',
    'Diploma In Agriculture': 'Diploma in General Agriculture',
    'Diploma In Agriculture , Human Ecology And Consumer Science': 'Diploma in General Agriculture',
    'Diploma In Agriculture And Biotechnology': 'Diploma in General Agriculture',
    'Diploma In Agripreneurship': 'Diploma in Agripreneurship',
    'Diploma In Agripreneurship (Cbet)': 'Diploma in Agripreneurship',
    'Diploma In Entrepreneurial Agriculture': 'Diploma in Agripreneurship',
    'Diploma In Enterpreneural Agriculture': 'Diploma in Agripreneurship',
    'Diploma In Farm Business Management': 'Diploma in Farm Business Management',
    'Diploma In Agribusiness Management': 'Diploma in Agribusiness Management',
    'Diploma In Agricultural Education And Extension': 'Diploma in Agricultural Extension',
    'Diploma In Agricultural Extension': 'Diploma in Agricultural Extension',
    'Diploma In Agricultural Extension (Cbet Level 6)': 'Diploma in Agricultural Extension',
    'Diploma In Agricultural Extension And Community Development': 'Diploma in Agricultural Extension',
    'Diploma In Horticulture': 'Diploma in Horticulture Production',
    'Diploma In Horticultural Production': 'Diploma in Horticulture Production',
    'Diploma In Horticulture Production': 'Diploma in Horticulture Production',
    'Diploma In Horticulture Production (Cbet)': 'Diploma in Horticulture Production',
    'Diploma In Animal Health': 'Diploma in Animal Health & Production',
    'Diploma In Animal Production And Health Management': 'Diploma in Animal Health & Production',
    'Diploma In Fisheries And Aquatic Sciences': 'Diploma in Fisheries & Aquatic Sciences',
    'Diploma In Aquaculture': 'Diploma in Aquaculture',
    'Diploma In Dairy Farm Management': 'Diploma in Dairy Farm Management',
    'Diploma In Applied Biology': 'Diploma in Applied Biology',
    'Diploma In Applied Chemistry': 'Diploma in Applied Chemistry',
    'Diploma In Analytical Chemistry': 'Diploma in Analytical Chemistry',
    'Diploma In Industrial Chemistry': 'Diploma in Industrial Chemistry',
    'Diploma In Food Science & Processing Technology': 'Diploma in Food Science & Technology',
    'Diploma In Food Science And Processing Technology': 'Diploma in Food Science & Technology',
    'Diploma In Food Science And Technology': 'Diploma in Food Science & Technology',
    'Diploma In Food Science Technology': 'Diploma in Food Science & Technology',
    'Diploma In Food Technology': 'Diploma in Food Science & Technology',
    'Diploma In Food Technology & Quality Assurance': 'Diploma in Food Science & Technology',
    'Diploma In Science Lab Technologist': 'Diploma in Science Laboratory Technology',
    'Diploma In Science Laboratory Technology': 'Diploma in Science Laboratory Technology',
    # HOSPITALITY & TOURISM
    'Diploma In Catering & Accommodation Management': 'Diploma in Catering & Accommodation Management',
    'Diploma In Catering & Accommodation Opertions': 'Diploma in Catering & Accommodation Management',
    'Diploma In Catering And Accommodation': 'Diploma in Catering & Accommodation Management',
    'Diploma In Catering And Accommodation Management': 'Diploma in Catering & Accommodation Management',
    'Diploma In Catering And Hotel Management': 'Diploma in Catering & Accommodation Management',
    'Diploma In  Hospitality Management': 'Diploma in Tourism & Hospitality Management',
    'Diploma In Tourism And Hospitality Management': 'Diploma in Tourism & Hospitality Management',
    'Diploma In International Tourism': 'Diploma in Tourism & Hospitality Management',
    'Diploma In Tourism Management': 'Diploma in Tourism & Hospitality Management',
    'Diploma In Travel,Tourism & Hospitality': 'Diploma in Tourism & Hospitality Management',
    'Diploma In Tour Guiding': 'Diploma in Tour Guiding',
    'Diploma In Tour Guiding And Travels': 'Diploma in Tour Guiding',
    'Diploma In Tour Guiding Management': 'Diploma in Tour Guiding',
    'Diploma In Food & Beverage': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food & Beverage Management': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food & Beverage Prod,Sales & Services Management': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food & Beverage Production & Sales Services': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food & Beverage Production,Sales & Service Management': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food & Beverages Production': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage Management': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage Production And Service Management': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage Production,Sales And Services': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage Sales Management': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage(Production And Service)': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverage,Production And Service': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverages': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food And Beverages Production, Sales & Service Management.': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Food Production-Culinary Level Six(Tvet-Cdacc)': 'Diploma in Food & Beverage Production & Service Management',
    'Diploma In Housekeeping And Accommodation Management': 'Diploma in Housekeeping & Accommodation Management',
    'Diploma In Housekeeping And Laundry': 'Diploma in Housekeeping & Accommodation Management',
    'Diploma In Housekeeping Management': 'Diploma in Housekeeping & Accommodation Management',
    'Diploma In Front Office Operations And Customer Care': 'Diploma in Front Office Operations',
    'Diploma In Reception Duties': 'Diploma in Front Office Operations',
    'Diploma In Fitness Instruction And Recreation Management': 'Diploma in Fitness & Recreation Management',
    'Diploma In Baking Technology': 'Diploma in Baking Technology',
    # MEDIA & COMMUNICATIONS
    'Diploma In Journalism': 'Diploma in Journalism',
    'Diploma In Broadcast Journalism': 'Diploma in Journalism',
    'Diploma In Digital Journalism': 'Diploma in Journalism',
    'Diploma In Journalism & Media': 'Diploma in Journalism',
    'Diploma In Film Video Programmes Production (Camera Option)': 'Diploma in Film & Video Production',
    'Diploma In Film Video Programmes Production (Directing Option)': 'Diploma in Film & Video Production',
    'Diploma In Film Video Programmes Production (Editing Option)': 'Diploma in Film & Video Production',
    'Diploma In Film Video Programmes Production (Sound Option)': 'Diploma in Film & Video Production',
    'Diploma In Television Programmes Production': 'Diploma in Television Production',
    'Diploma In Radio Programmes Production & Broadcasting': 'Diploma in Radio Production & Broadcasting',
    'Diploma In Library & Information Science': 'Diploma in Library & Information Science',
    'Diploma In Library & Information Studies': 'Diploma in Library & Information Science',
    'Diploma In Library & Information Studies Level Six (Tvet-Cdacc)': 'Diploma in Library & Information Science',
    'Diploma In Library And Information Science': 'Diploma in Library & Information Science',
    'Diploma In Library And Information Studies': 'Diploma in Library & Information Science',
    'Diploma In Librarian And Information Science': 'Diploma in Library & Information Science',
    'Diploma In Archives And Records Management': 'Diploma in Archives & Records Management',
    'Diploma In Music And Dance': 'Diploma in Music & Performing Arts',
    # SOCIAL SCIENCES & COMMUNITY
    'Diploma In Social Work': 'Diploma in Social Work & Community Development',
    'Diploma In Social Work & Community Development': 'Diploma in Social Work & Community Development',
    'Diploma In Social Work And Community Development': 'Diploma in Social Work & Community Development',
    'Diploma In Social Work And Development': 'Diploma in Social Work & Community Development',
    'Diploma In Social Work And Social Development': 'Diploma in Social Work & Community Development',
    'Diploma In Social Work& Community Development': 'Diploma in Social Work & Community Development',
    'Diploma In Community Development And Social Work': 'Diploma in Social Work & Community Development',
    'Diploma In Community Development': 'Diploma in Community Development',
    'Diploma In Community And Civic Development': 'Diploma in Community Development',
    'Diploma In Community Development And Counselling': 'Diploma in Community Development',
    'Diploma In Counselling Psychology': 'Diploma in Guidance & Counselling',
    'Diploma In Guidance And Counselling': 'Diploma in Guidance & Counselling',
    'Diploma In Early Childhood Development': 'Diploma in Early Childhood Education',
    'Diploma In Early Childhood Education': 'Diploma in Early Childhood Education',
    'Diploma In Criminology And Criminal Justice': 'Diploma in Criminology & Criminal Justice',
    'Diploma In Security And Intelligence Studies': 'Diploma in Security & Intelligence Studies',
    'Diploma In Child Care And Protection': 'Diploma in Child Care & Protection',
    'Diploma In Child Protection': 'Diploma in Child Care & Protection',
    'Diploma In Disaster Management': 'Diploma in Disaster Management',
    # ENVIRONMENT & NATURAL RESOURCES
    'Diploma In Enviromental Science And Technology': 'Diploma in Environmental Science & Technology',
    'Diploma In Environmental Management': 'Diploma in Environmental Science & Technology',
    'Diploma In Environmental Science': 'Diploma in Environmental Science & Technology',
    'Diploma In Environmental Science And Technology': 'Diploma in Environmental Science & Technology',
    'Diploma In Environmental Sciences': 'Diploma in Environmental Science & Technology',
    'Diploma In Nautical Sciences': 'Diploma in Nautical Sciences',
    'Diploma In Wildlife Management': 'Diploma in Wildlife Management',
    # BUILT ENVIRONMENT
    'Diploma In Architecture': 'Diploma in Architecture',
    'Diploma In Architectural Design': 'Diploma in Architecture',
    'Diploma In Architecture Engineering': 'Diploma in Architecture',
    'Diploma In Quantity Survey': 'Diploma in Quantity Surveying',
    'Diploma In Quantity Surveying': 'Diploma in Quantity Surveying',
    'Diploma In Land Surveying': 'Diploma in Land Surveying',
    'Diploma In Photogrammetry & Remote Sensing': 'Diploma in Photogrammetry & Remote Sensing',
    'Diploma In Cartography': 'Diploma in Cartography',
    # FASHION & DESIGN
    'Diploma In Fashion & Garment Making': 'Diploma in Fashion Design & Garment Making',
    'Diploma In Fashion Design': 'Diploma in Fashion Design & Garment Making',
    'Diploma In Fashion Design & Clothing': 'Diploma in Fashion Design & Clothing Technology',
    'Diploma In Fashion Design & Clothing Technology': 'Diploma in Fashion Design & Clothing Technology',
    'Diploma In Fashion Design & Garment Making': 'Diploma in Fashion Design & Garment Making',
    'Diploma In Fashion Design & Garment Making Technology': 'Diploma in Fashion Design & Garment Making',
    'Diploma In Fashion Design & Textile Technology': 'Diploma in Fashion Design & Clothing Technology',
    'Diploma In Fashion Design And Clothing': 'Diploma in Fashion Design & Clothing Technology',
    'Diploma In Fashion Design And Clothing Technology': 'Diploma in Fashion Design & Clothing Technology',
    'Diploma In Fashion Design And Garment Making': 'Diploma in Fashion Design & Garment Making',
    'Diploma In Fashion Design And Garment Making Technology': 'Diploma in Fashion Design & Garment Making',
    'Diploma In Clothing & Textile': 'Diploma in Clothing & Textile Technology',
    'Diploma In Clothing Technology': 'Diploma in Clothing & Textile Technology',
    # TRANSPORT & LOGISTICS
    'Diploma In Transport Management': 'Diploma in Transport Management',
    'Diploma In Road Transport Management': 'Diploma in Transport Management',
    'Diploma In Shipping And Logistics': 'Diploma in Shipping & Logistics',
    'Diploma In Air Cargo Management': 'Diploma in Air Cargo Management',
    'Diploma In Airport Operations': 'Diploma in Airport Operations',
    'Diploma In Flight Operations/Dispatch': 'Diploma in Flight Operations & Dispatch',
    'Diploma In Freight Management': 'Diploma in Freight Management',
    'Diploma In Technology (Tourism And Travel Management)': 'Diploma in Tourism & Hospitality Management',
    'Diploma In Technology (Instrumentation & Control)': 'Diploma in Electrical & Electronics Engineering (Instrumentation)',
    # SURVEY/MAPPING
    'Diploma In Applied Statistics': 'Diploma in Applied Statistics',
    # EXCLUDE: Teacher training programmes
    'Diploma In Secondary Teacher Education  In Agriculture  And Biology': None,
    'Diploma In Secondary Teacher Education  In Agriculture  And Chemistry': None,
    'Diploma In Secondary Teacher Education In English And Christian Religious Education': None,
    'Diploma In Secondary Teacher Education In English And Geography': None,
    'Diploma In Secondary Teacher Education In Kiswahili And Christian Religious Education': None,
    'Diploma In Secondary Teacher Education In Kiswahili And Geography': None,
    'Diploma In Secondary Teacher Education, Biology / Chemistry': None,
    'Diploma In Secondary Teachers Education In Arabic And English': None,
    'Diploma In Secondary Teachers Education In Arabic And Ire': None,
    'Diploma In Secondary Teachers Education In Business Studies And Mathematics': None,
    'Diploma In Secondary Teachers Education In English And Cre': None,
    'Diploma In Secondary Teachers Education In English And History': None,
    'Diploma In Secondary Teachers Education In English And Ire': None,
    'Diploma In Secondary Teachers Education In Fasihi Ya Kiswahili And Geog': None,
    'Diploma In Secondary Teachers Education In French And English': None,
    'Diploma In Secondary Teachers Education In German And English': None,
    'Diploma In Secondary Teachers Education In Kiswahili And Cre': None,
    'Diploma In Secondary Teachers Education In Kiswahili And History': None,
    'Diploma In Secondary Teachers Education In Mathematics And Geography': None,
    'Diploma In Secondary Teachers Education In Physics And Mathematics': None,
    'Diploma In Secondary Teachers Education, Chemistry And Mathematics': None,
    'Diploma In Teacher Education (Art And Design / English )': None,
    'Diploma In Teacher Education (Art And Design / Kiswahili)': None,
    'Diploma In Teacher Education (Biology/Mathematics)': None,
    'Diploma In Teacher Education (French/Geography Or History Or C.R.E Or English)': None,
    'Diploma In Teacher Education (Geography / Business Studies)': None,
    'Diploma In Teacher Education (Geography/ History)': None,
    'Diploma In Teacher Education (Geography/Christian Religious Education)': None,
    'Diploma In Teacher Education (German/ English Or C.R.E Or History Or Geography)': None,
    'Diploma In Teacher Education (Kiswahili / History)': None,
    'Diploma In Teacher Education (Physics / Computer Studies)': None,
    'Diploma In Teacher Education (Physics/Chemistry)': None,
}

# ─────────────────────────────────────────────────────────────────────────────
# 2. Apply canonical map to offerings, drop excluded
# ─────────────────────────────────────────────────────────────────────────────
clean_offerings = []
unmapped = set()
for o in raw['offerings']:
    canonical = CANONICAL_MAP.get(o['programme'])
    if canonical is None:
        if o['programme'] in CANONICAL_MAP:
            continue  # excluded
        else:
            unmapped.add(o['programme'])
            canonical = o['programme']  # keep raw as fallback
    clean_offerings.append({'code': o['code'], 'institution': o['institution'], 'programme': canonical})

print(f"Clean offerings: {len(clean_offerings)}")
print(f"Unmapped (kept as-is): {len(unmapped)}")
if unmapped:
    print("Unmapped programmes:")
    for u in sorted(unmapped):
        print(f"  {u}")

# ─────────────────────────────────────────────────────────────────────────────
# 3. Unique canonical programmes
# ─────────────────────────────────────────────────────────────────────────────
canonical_programmes = sorted(set(o['programme'] for o in clean_offerings))
print(f"\nUnique canonical programmes: {len(canonical_programmes)}")
for p in canonical_programmes:
    print(f"  {p}")

with open('tvet_clean_offerings.json', 'w', encoding='utf-8') as f:
    json.dump({'offerings': clean_offerings, 'programmes': canonical_programmes}, f, indent=2)

print("\nSaved tvet_clean_offerings.json")
