"""
Django settings for kuccpss project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if present
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-do-not-use-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',
    'careernext.co.ke',
    'www.careernext.co.ke',
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://careernext.co.ke',
    'https://www.careernext.co.ke',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'clusterpoints',
    'widget_tweaks',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'clusters',
    'institutions',
    'courses',
    'career',
    'resources',
    'payments',
    'import_export',
    'predictor',
    'analytics',
    'mentorship',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.sitemaps',
]

# ── Media storage ─────────────────────────────────────────────────────────────
# In production CLOUDINARY_URL is set as an env var (cloudinary://key:secret@cloud).
# Locally, files are served from MEDIA_ROOT as usual.
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
if CLOUDINARY_URL:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = 'https://res.cloudinary.com/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email — uses Resend REST API in production (avoids SMTP port blocks on Render free tier),
# falls back to console backend in dev so you see emails in the terminal
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
if RESEND_API_KEY:
    EMAIL_BACKEND = 'kuccpss.email_backends.ResendEmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'CareerNext <noreply@careernext.co.ke>')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'limomeshk@gmail.com')

TIME_ZONE = 'Africa/Nairobi'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'kuccpss.middleware.GracefulErrorMiddleware',
    'kuccpss.middleware.HeavyEndpointRateLimitMiddleware',
    'kuccpss.middleware.SlowRequestLogMiddleware',
    'kuccpss.middleware.DisableHttp3Middleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'kuccpss.middleware.ReferralMiddleware',
]

# ── Data versioning — update each KUCCPS cycle ───────────────────────────────
# These constants appear in templates and results pages so students always know
# which cycle's data they are viewing.
DATA_VERSION    = os.environ.get('DATA_VERSION', '2024')
DATA_CYCLE      = os.environ.get('DATA_CYCLE', '2025/2026')
DATA_UPDATED    = os.environ.get('DATA_UPDATED', 'March 2025')

ROOT_URLCONF = 'kuccpss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.unread_notifications',
                'analytics.context_processors.posthog_keys',
                'analytics.context_processors.sentry_context',
                'analytics.context_processors.ga_context',
                'analytics.context_processors.data_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'kuccpss.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'kuccpss'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

# ── Caching ───────────────────────────────────────────────────────────────────
# Local-memory by default (zero dependencies, works on Render free tier).
# Automatically upgrades to Redis when REDIS_URL env var is set.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'careernext-v1',
        'TIMEOUT': 300,
        'OPTIONS': {'MAX_ENTRIES': 3000},
    }
}
_REDIS_URL = os.environ.get('REDIS_URL')
if _REDIS_URL:
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': _REDIS_URL,
        'TIMEOUT': 300,
        'OPTIONS': {'max_connections': 20},
        'KEY_PREFIX': 'cn',
    }

# Serve sessions from cache first, fall back to DB — avoids a DB hit on every request
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'


# IntaSend M-Pesa
INTASEND_PUBLISHABLE_KEY = os.environ.get("INTASEND_PUBLISHABLE_KEY", "")
INTASEND_SECRET_KEY = os.environ.get("INTASEND_SECRET_KEY", "")
INTASEND_WEBHOOK_SECRET = os.environ.get("INTASEND_WEBHOOK_SECRET", "")
INTASEND_SANDBOX = os.environ.get("INTASEND_SANDBOX", "true").lower() == "true"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SITE_ID = int(os.environ.get('SITE_ID', 1))
AUTH_USER_MODEL = "accounts.User"
LOGIN_REDIRECT_URL = "/accounts/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Session: 90-day max (individual views call set_expiry() to match user type)
SESSION_COOKIE_AGE = 90 * 24 * 3600  # 90 days

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none' if os.environ.get('DJANGO_DEBUG', 'True') != 'True' else 'optional'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'FETCH_USERINFO': True,
    }
}
# build.sh creates/updates the DB SocialApp from GOOGLE_CLIENT_ID + GOOGLE_SECRET env vars.
# Templates use this flag to hide the Google button when credentials are not configured.
_google_client_id = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_OAUTH_AVAILABLE = bool(_google_client_id)




OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

# PostHog analytics — JS key is public; Python key stays server-side
POSTHOG_API_KEY  = os.environ.get("POSTHOG_API_KEY", "")
POSTHOG_HOST     = os.environ.get("POSTHOG_HOST", "https://eu.i.posthog.com")
# Optional: paste the iframe src from PostHog → Dashboard → Share → Embed
POSTHOG_EMBED_URL = os.environ.get("POSTHOG_EMBED_URL", "")

# Google Analytics 4 — set GA_MEASUREMENT_ID env var (e.g. G-XXXXXXXXXX)
GA_MEASUREMENT_ID = os.environ.get("GA_MEASUREMENT_ID", "")

# Affiliate payout — admin WhatsApp number for payout requests
AFFILIATE_PAYOUT_PHONE = os.environ.get("AFFILIATE_PAYOUT_PHONE", "254700000000")

# Web Push (VAPID)
import base64 as _b64
VAPID_PUBLIC_KEY  = os.environ.get("VAPID_PUBLIC_KEY", "")
_vapid_priv_b64   = os.environ.get("VAPID_PRIVATE_KEY", "")
# Add padding if stripped (common when copying base64 keys)
if _vapid_priv_b64:
    _vapid_priv_b64 += "=" * (-len(_vapid_priv_b64) % 4)
VAPID_PRIVATE_KEY = _b64.b64decode(_vapid_priv_b64).decode() if _vapid_priv_b64 else ""
VAPID_MAILTO      = os.environ.get("VAPID_MAILTO", "info@careernext.co.ke")

# Render / production database — overrides individual DB_* vars if set
_DATABASE_URL = os.environ.get('DATABASE_URL')
if _DATABASE_URL:
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(_DATABASE_URL, conn_max_age=600, ssl_require=True)

# ── Production security ───────────────────────────────────────────────────────
if not DEBUG:
    # Crash loudly if SECRET_KEY is still the insecure fallback
    if SECRET_KEY.startswith('django-insecure-'):
        raise RuntimeError("SECRET_KEY must be set via environment variable in production.")

    # Render terminates TLS at its edge; tell Django the real proto via the header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS: browsers remember to use HTTPS for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies must only travel over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent browsers from MIME-sniffing responses
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Additional cookie hardening
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

# Structured logging — ERROR+ always goes to stdout (Render captures it).
# In DEBUG mode lower to WARNING so slow requests and app warnings are visible.
_LOG_LEVEL = 'WARNING' if DEBUG else 'ERROR'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': _LOG_LEVEL,
        },
        'django.request': {
            'handlers': ['console'],
            'level': _LOG_LEVEL,
            'propagate': False,
        },
        # App-level loggers — WARNING+ always captured
        'kuccpss': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'clusterpoints': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'career': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'courses': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'payments': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

# ── Sentry error monitoring ───────────────────────────────────────────────────
# Only initialises when SENTRY_DSN is set; completely silent in local dev.
_SENTRY_DSN  = os.environ.get('SENTRY_DSN', '')
# Build a consistent release string shared by both backend and frontend JS SDK.
# Render injects RENDER_GIT_COMMIT (full SHA) on every deploy.
SENTRY_RELEASE      = os.environ.get('RENDER_GIT_COMMIT', '') or None
SENTRY_ENVIRONMENT  = 'production' if not DEBUG else 'development'

if _SENTRY_DSN:
    import logging as _logging
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    from django.http import Http404
    from django.core.exceptions import BadRequest, PermissionDenied, SuspiciousOperation

    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        integrations=[
            DjangoIntegration(
                transaction_style='url',  # group by URL pattern, not function name
                middleware_spans=True,
                signals_spans=False,      # Django signals are too noisy
                cache_spans=False,
            ),
            LoggingIntegration(
                level=_logging.WARNING,       # WARNING+ captured as breadcrumbs
                event_level=_logging.ERROR,   # ERROR+ sent as Sentry events
            ),
        ],
        # Highlight CareerNext frames vs Django/library internals in every trace.
        in_app_include=[
            'accounts', 'clusters', 'clusterpoints', 'institutions',
            'courses', 'career', 'resources', 'payments', 'predictor',
            'analytics', 'mentorship', 'kuccpss',
        ],
        # Performance: sample 10 % of requests; tune via env var without redeploy.
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_RATE', '0.1')),
        profiles_sample_rate=float(os.environ.get('SENTRY_PROFILES_RATE', '0.05')),
        # Attach a stack trace to every captured log message (not just exceptions).
        attach_stacktrace=True,
        # Never send PII — no emails, IPs, cookies, or auth headers.
        send_default_pii=False,
        max_breadcrumbs=50,
        # Ignore expected / non-actionable exceptions to keep the issue list clean.
        ignore_errors=[
            Http404,
            PermissionDenied,
            SuspiciousOperation,  # covers DisallowedHost, CSRF failures, bad headers
            BadRequest,
        ],
    )