# Generated by Django 6.0.6 on 2026-06-15 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerEngineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pathway",
                    models.CharField(
                        choices=[
                            ("degree", "Degree"),
                            ("diploma", "Diploma"),
                            ("kmtc", "KMTC"),
                            ("certificate", "Certificate"),
                            ("artisan", "Artisan"),
                            ("ttc", "TTC"),
                            ("shortcourse", "Short Course"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("result_count", models.PositiveSmallIntegerField(default=0)),
                ("mean_grade", models.CharField(blank=True, max_length=5)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pathway", "created_at"],
                        name="analytics_c_pathway_f57dd6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("resource_pdf", "Resource PDF"),
                            ("course_pdf", "Course PDF"),
                            ("institution_pdf", "Institution PDF"),
                            ("career_pdf", "Career Engine PDF"),
                            ("cluster_pdf", "Cluster Points PDF"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("object_name", models.CharField(blank=True, max_length=250)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type"], name="analytics_d_content_807cd0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_d_created_198f87_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=300)),
                ("result_count", models.PositiveSmallIntegerField(default=0)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["query"], name="analytics_s_query_86cb43_idx"),
                    models.Index(
                        fields=["created_at"], name="analytics_s_created_269249_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("institution", "Institution"),
                            ("career_profile", "Career Profile"),
                            ("resource", "Resource"),
                            ("article", "Article"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("object_name", models.CharField(blank=True, max_length=250)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="analytics_v_content_55b806_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_v_created_998358_idx"
                    ),
                ],
            },
        ),
    ]
