# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_eventlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(
                fields=["session_key"], name="analytics_s_session_4154c4_idx"
            ),
        ),
    ]
