# Generated by Django 5.2.15 on 2026-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_sessionlog_geo"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pageviewlog",
            new_name="analytics_p_path_8a12c2_idx",
            old_name="analytics_p_path_ca_idx",
        ),
        migrations.RenameIndex(
            model_name="pageviewlog",
            new_name="analytics_p_status__2f52e5_idx",
            old_name="analytics_p_status_ca_idx",
        ),
        migrations.RenameIndex(
            model_name="pageviewlog",
            new_name="analytics_p_device_97b0c4_idx",
            old_name="analytics_p_device_ca_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionlog",
            new_name="analytics_s_created_465f33_idx",
            old_name="analytics_s_created_idx",
        ),
        migrations.RenameIndex(
            model_name="useractionlog",
            new_name="analytics_u_action_70b259_idx",
            old_name="analytics_u_action_ca_idx",
        ),
        migrations.RenameIndex(
            model_name="useractionlog",
            new_name="analytics_u_created_541621_idx",
            old_name="analytics_u_created_idx",
        ),
        migrations.AlterField(
            model_name="viewlog",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("institution", "Institution"),
                    ("career_profile", "Career Profile"),
                    ("resource", "Resource"),
                    ("article", "Article"),
                    ("mentor_profile", "Mentor Profile"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
