# Generated by Django 5.2.15 on 2026-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_schedule_purge_old_logs"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="downloadlog",
            name="analytics_d_content_807cd0_idx",
        ),
        migrations.RemoveIndex(
            model_name="downloadlog",
            name="analytics_d_created_198f87_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventlog",
            name="analytics_e_created_4575fe_idx",
        ),
        migrations.RemoveIndex(
            model_name="searchlog",
            name="analytics_s_query_86cb43_idx",
        ),
        migrations.RemoveIndex(
            model_name="searchlog",
            name="analytics_s_created_269249_idx",
        ),
        migrations.RemoveIndex(
            model_name="sessionlog",
            name="analytics_s_created_465f33_idx",
        ),
        migrations.RemoveIndex(
            model_name="useractionlog",
            name="analytics_u_created_541621_idx",
        ),
        migrations.RemoveIndex(
            model_name="viewlog",
            name="analytics_v_created_998358_idx",
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="pageviewlog",
            name="device",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("tablet", "Tablet"),
                    ("desktop", "Desktop"),
                    ("bot", "Bot / Crawler"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pageviewlog",
            name="path",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="pageviewlog",
            name="status_code",
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("shortlist_add", "Shortlist Add"),
                    ("shortlist_remove", "Shortlist Remove"),
                    ("compare_add", "Compare Add"),
                    ("compare_remove", "Compare Remove"),
                    ("profile_update", "Profile Update"),
                    ("share", "Share"),
                    ("ai_chat", "AI Chat Message"),
                    ("quiz_start", "Quiz Start"),
                    ("quiz_complete", "Quiz Complete"),
                    ("calculator_run", "Calculator Run"),
                    ("referral_click", "Referral Click"),
                    ("email_verified", "Email Verified"),
                    ("password_reset", "Password Reset"),
                ],
                max_length=30,
            ),
        ),
    ]
