# Generated by Django 6.0.6 on 2026-06-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0002_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="portal_screenshot",
            field=models.FileField(
                blank=True,
                help_text="Screenshot from your university portal showing Name, Reg No, Course, and Year/Semester.",
                null=True,
                upload_to="mentor_docs/portal_screenshots/",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="student_id_upload",
            field=models.FileField(
                blank=True,
                help_text="Photo or scan of your student ID card.",
                null=True,
                upload_to="mentor_docs/student_ids/",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="university_email",
            field=models.EmailField(
                blank=True,
                help_text="Your institutional email, e.g. jm001@students.jkuat.ac.ke. Optional but increases approval chances.",
                max_length=254,
            ),
        ),
    ]
