# Generated by Django 6.0.6 on 2026-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0003_mentor_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="is_rejected",
            field=models.BooleanField(
                default=False,
                help_text="Set by admin on rejection — permanently prevents reapplication.",
            ),
        ),
    ]
