# Generated by Django 6.0.6 on 2026-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0004_add_is_rejected_to_mentorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorshipConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_price",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Amount (KES) the student pays per session.",
                    ),
                ),
                (
                    "mentor_payout",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="Amount (KES) the mentor earns per completed session. Must be less than session_price.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentorship Pricing Config",
                "verbose_name_plural": "Mentorship Pricing Config",
            },
        ),
    ]
