# Generated by Django 6.0.6 on 2026-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0005_add_mentorshipconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="custom_mentor_payout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override global mentor payout for this mentor only. Leave blank to use the global default.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="custom_session_price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override global session price for this mentor only. Leave blank to use the global default.",
                null=True,
            ),
        ),
    ]
