# Generated by Django 6.0.6 on 2026-06-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0006_add_per_mentor_price_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="meet_link",
            field=models.URLField(
                blank=True,
                help_text="Google Meet or Jitsi video call link for this session",
            ),
        ),
    ]
