# Generated by Django 6.0.6 on 2026-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0007_mentorshipsession_meet_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="manual_payment_ref",
            field=models.CharField(
                blank=True,
                help_text="M-Pesa transaction code entered by mentee for manual payment verification.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="mentee_phone",
            field=models.CharField(
                blank=True,
                help_text="Mentee's phone number — shared with mentor after payment confirmation.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("pending_manual_verification", "Pending Manual Verification"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=30,
            ),
        ),
    ]
