# Generated by Django 6.0.6 on 2026-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0008_add_mentee_phone_manual_ref_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipconfig",
            name="mentor_signup_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show or hide the 'Become a Mentor' button across the entire site.",
            ),
        ),
    ]
