# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_courses_cou_course__320d41_idx_and_more"),
        ("institutions", "0005_institution_institution_institu_7ec5c7_idx_and_more"),
        ("mentorship", "0009_add_mentor_signup_enabled_to_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["is_approved", "is_active"],
                name="mentorship__is_appr_095597_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["average_rating"], name="mentorship__average_222ba4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshipsession",
            index=models.Index(
                fields=["mentor", "status"], name="mentorship__mentor__5dfe8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshipsession",
            index=models.Index(
                fields=["mentee", "created_at"], name="mentorship__mentee__9d089a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["date", "is_booked"], name="mentorship__date_0e0782_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["mentor", "date"], name="mentorship__mentor__a73221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["mentor", "status"], name="mentorship__mentor__b6591a_idx"
            ),
        ),
    ]
