# Generated by Django 5.2.15 on 2026-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0010_mentorprofile_mentorship__is_appr_095597_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("processed", "Processed"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
