# Generated by Django 5.2.15 on 2026-07-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0011_alter_withdrawalrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorshipsession",
            name="meet_link",
        ),
    ]
