# Generated by Django 5.2.15 on 2026-09-26 10:50

import kuccpss.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0012_remove_mentorshipsession_meet_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mentor_photos/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="portal_screenshot",
            field=models.FileField(
                blank=True,
                help_text="Screenshot from your university portal showing Name, Reg No, Course, and Year/Semester.",
                null=True,
                upload_to="mentor_docs/portal_screenshots/",
                validators=[kuccpss.upload_validators.SafeDocumentValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="student_id_upload",
            field=models.FileField(
                blank=True,
                help_text="Photo or scan of your student ID card.",
                null=True,
                upload_to="mentor_docs/student_ids/",
                validators=[kuccpss.upload_validators.SafeDocumentValidator()],
            ),
        ),
    ]
