# Generated by Django 5.2.15 on 2026-10-01 09:31

from django.db import migrations, models


def _fail_duplicate_pending(apps, schema_editor, app_label, model_name, owner_field):
    """Leave at most one pending withdrawal per mentor so the new partial unique
    constraint can be created. Older duplicates become 'failed' — like 'pending',
    a failed request never debited the wallet, and admin can still process it."""
    Model = apps.get_model(app_label, model_name)
    seen = set()
    for wr in Model.objects.filter(status="pending").order_by("-created_at", "-pk"):
        owner = getattr(wr, owner_field + "_id")
        if owner in seen:
            Model.objects.filter(pk=wr.pk).update(
                status="failed",
                admin_note=(wr.admin_note + " | " if wr.admin_note else "")
                + "Auto-failed by migration: duplicate pending withdrawal",
            )
        seen.add(owner)


def dedupe_pending(apps, schema_editor):
    _fail_duplicate_pending(apps, schema_editor, "mentorship", "WithdrawalRequest", "mentor")


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0013_alter_mentorprofile_photo_and_more"),
    ]

    operations = [
        migrations.RunPython(dedupe_pending, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("mentor",),
                name="one_pending_withdrawal_per_mentor",
            ),
        ),
    ]
