# Generated by Django 5.2.15 on 2026-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0014_db_integrity_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
