# Generated by Django 5.2.15 on 2026-10-04 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_db_index_cleanup"),
        ("mentorship", "0015_mentorshipsession_reminder_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorshipsession",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="mentorship.timeslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorshipsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "pending_payment",
                            "pending_manual_verification",
                            "confirmed",
                            "completed",
                        ),
                    )
                ),
                fields=("slot",),
                name="one_active_session_per_slot",
            ),
        ),
    ]
