# Generated by Django 5.2.15 on 2026-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0016_slot_rebooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="payout_debt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
