# Generated by Django 5.2.15 on 2026-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0017_mentor_payout_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorshipsession",
            name="refund_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="refund_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="refund_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
