# Generated by Django 5.2.15 on 2026-10-04 23:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_db_index_cleanup"),
        ("institutions", "0007_db_index_cleanup"),
        ("mentorship", "0018_session_refund_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="custom_session_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Override global session length (minutes) for this mentor only. Leave blank to use the global default.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(240),
                ],
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Expert mentors only — lower numbers are listed first.",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Expert mentors only — shown in place of course/year, e.g. 'Career Counsellor · 15 yrs experience'.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="mentor_type",
            field=models.CharField(
                choices=[("student", "Student mentor"), ("expert", "Expert mentor")],
                db_index=True,
                default="student",
                help_text="Expert mentors are professionals who advise on any course. They are listed above student mentors and are added by admin, not via the signup form.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mentorshipconfig",
            name="session_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Default session length in minutes. Override per mentor on the mentor's profile.",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(240),
                ],
            ),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="course_topic",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="mentorshipsession",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentors",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentors",
                to="institutions.institution",
            ),
        ),
    ]
