# Generated by Django 5.2.15 on 2026-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0019_expert_mentors_session_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="show_new_badge",
            field=models.BooleanField(
                default=False,
                help_text="Show the 'New mentor' badge on this mentor's card and profile.",
            ),
        ),
    ]
