# Generated by Django 5.2.15 on 2026-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0020_mentor_show_new_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="show_expert_badge",
            field=models.BooleanField(
                default=False,
                help_text="Show the 'Expert' badge next to this mentor's name on their card and profile.",
            ),
        ),
    ]
