# Generated by Django 5.2.15 on 2026-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0021_mentor_show_expert_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Student mentors only — pin to the top of the directory, above mentors with more sessions.",
            ),
        ),
    ]
