# Generated by Django 6.0.6 on 2026-06-10 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_savedcareer_savedcourse_user_county_user_kcse_year_and_more",
        ),
        (
            "career",
            "0002_quizquestion_careerprofile_quizoption_quizsubmission_and_more",
        ),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcareer",
            name="career_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="career.careerprofile",
            ),
        ),
        migrations.AddField(
            model_name="savedcareer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_careers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="savedcourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="accounts_no_user_id_a4ff2e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedcareer",
            unique_together={("user", "career_profile")},
        ),
        migrations.AlterUniqueTogether(
            name="savedcourse",
            unique_together={("user", "course")},
        ),
    ]
