# Generated by Django 6.0.6 on 2026-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_notification_published_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseshortlist",
            options={"ordering": ["rank", "-added_at"]},
        ),
        migrations.AddField(
            model_name="courseshortlist",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Personal notes for this course"
            ),
        ),
        migrations.AddField(
            model_name="courseshortlist",
            name="rank",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="KUCCPS choice order (1 = first choice, up to 4)",
                null=True,
            ),
        ),
    ]
