# Generated by Django 6.0.6 on 2026-06-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_growth_models"),
        ("payments", "0004_seed_payment_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Percentage of each payment awarded as commission",
                        max_digits=5,
                    ),
                ),
                (
                    "wallet_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pending payout in KES",
                        max_digits=10,
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lifetime commissions earned in KES",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes (e.g. WhatsApp group admin, 8K members)",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_affiliates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Profile",
                "verbose_name_plural": "Affiliate Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Commission in KES", max_digits=10
                    ),
                ),
                (
                    "rate_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate at time of award (in case rate changes later)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payout"),
                            ("paid_out", "Paid Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_out_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_commission",
                        to="payments.payment",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="accounts.referral",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="accounts.affiliateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Commission",
                "verbose_name_plural": "Affiliate Commissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
