# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_affiliate_withdrawal_request"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("payments", "0009_payment_payments_pa_user_id_407fec_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="affiliatecommission",
            index=models.Index(
                fields=["affiliate", "status"], name="accounts_af_affilia_5498a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatewithdrawalrequest",
            index=models.Index(
                fields=["affiliate", "status"], name="accounts_af_affilia_79ef0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="accounts_ap_status_0d8e17_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "status"], name="accounts_ap_user_id_1088a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careersessionsnapshot",
            index=models.Index(
                fields=["user", "pathway"], name="accounts_ca_user_id_e34255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careersessionsnapshot",
            index=models.Index(
                fields=["user", "computed_at"], name="accounts_ca_user_id_1c11b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(
                fields=["expires_at", "is_used"], name="accounts_em_expires_518cf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["expires_at", "is_used"], name="accounts_pa_expires_5027b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remembertoken",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="accounts_re_expires_a7628e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["deleted_at"], name="accounts_us_deleted_08a5c0_idx"
            ),
        ),
    ]
