# Generated by Django 6.0.6 on 2026-06-29 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0013_affiliatecommission_accounts_af_affilia_5498a6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="EmailBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("heading", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="One paragraph per line. Each line becomes a separate paragraph."
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.URLField(blank=True)),
                (
                    "banner_color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("amber", "Amber"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                (
                    "send_to_leads",
                    models.BooleanField(
                        default=False,
                        help_text="Also send to captured email leads (non-registered visitors)",
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Broadcast",
                "verbose_name_plural": "Email Broadcasts",
                "ordering": ["-created_at"],
            },
        ),
    ]
