# Generated by Django 5.2.15 on 2026-09-26 10:50

import kuccpss.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_email_notifications_emailbroadcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
    ]
