# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="accounts_no_user_id_a4ff2e_idx",
        ),
        migrations.RemoveIndex(
            model_name="referral",
            name="accounts_re_code_6de444_idx",
        ),
        migrations.RemoveIndex(
            model_name="referral",
            name="accounts_re_referre_910ca4_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_email_74c8d6_idx",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="accounts_no_user_id_cabb0a_idx",
            ),
        ),
    ]
