# Generated by Django 5.2.15 on 2026-10-01 09:31

from django.db import migrations, models


def _fail_duplicate_pending(apps, schema_editor, app_label, model_name, owner_field):
    """Leave at most one pending withdrawal per affiliate so the new partial unique
    constraint can be created. Older duplicates become 'failed' — like 'pending',
    a failed request never debited the wallet, and admin can still process it."""
    Model = apps.get_model(app_label, model_name)
    seen = set()
    for wr in Model.objects.filter(status="pending").order_by("-created_at", "-pk"):
        owner = getattr(wr, owner_field + "_id")
        if owner in seen:
            Model.objects.filter(pk=wr.pk).update(
                status="failed",
                admin_note=(wr.admin_note + " | " if wr.admin_note else "")
                + "Auto-failed by migration: duplicate pending withdrawal",
            )
        seen.add(owner)


def dedupe_pending(apps, schema_editor):
    _fail_duplicate_pending(apps, schema_editor, "accounts", "AffiliateWithdrawalRequest", "affiliate")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_staff_totp_device"),
        ("payments", "0013_db_integrity_hardening"),
    ]

    operations = [
        migrations.RunPython(dedupe_pending, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="affiliatecommission",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="affiliate_commission_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="affiliateprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("wallet_balance__gte", 0)),
                name="affiliate_wallet_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="affiliateprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_earned__gte", 0)),
                name="affiliate_total_earned_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="affiliateprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commission_rate__gte", 0), ("commission_rate__lte", 100)
                ),
                name="affiliate_commission_rate_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="affiliatewithdrawalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="affiliate_withdrawal_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="affiliatewithdrawalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("affiliate",),
                name="one_pending_withdrawal_per_affiliate",
            ),
        ),
    ]
