# Generated by Django 5.2.8 on 2026-02-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon for UI cards', max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Optional hex color for UI', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Course Type',
                'verbose_name_plural': 'Course Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='courses_cou_name_0f84b6_idx'), models.Index(fields=['slug'], name='courses_cou_slug_27f5fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='courses.coursetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'course_type')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cutoff_points', models.JSONField(blank=True, help_text='Example: {"2024": 65, "2023": 62}', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, help_text='Only for university courses', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.cluster')),
                ('core_subjects', models.ManyToManyField(blank=True, to='courses.coresubject')),
                ('institutions', models.ManyToManyField(to='institutions.institution')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetype')),
            ],
            options={
                'ordering': ['course_type', 'category', 'name'],
                'indexes': [models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'), models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx')],
            },
        ),
    ]
