# Generated by Django 6.0.6 on 2026-06-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_delete_coresubject_alter_course_core_subjects"),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cutoff_points",
                    models.JSONField(
                        blank=True,
                        help_text='Per-institution cutoffs. Example: {"2024": 78.5, "2023": 76.2}',
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="courses.course",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Offering",
                "verbose_name_plural": "Course Offerings",
                "ordering": ["institution__name"],
                "unique_together": {("course", "institution")},
            },
        ),
        # Django cannot ALTER a M2M to add through= at the DB level.
        # We update the migration state only, and drop the old empty junction table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="course",
                    name="institutions",
                    field=models.ManyToManyField(
                        blank=True,
                        through="courses.CourseOffering",
                        to="institutions.institution",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS courses_course_institutions;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
