# Generated by Django 5.2.8 on 2026-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_courseoffering_through_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="minimum_mean_grade",
            field=models.CharField(
                blank=True, help_text="e.g. C, C-, D+", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject_requirements",
            field=models.JSONField(
                blank=True,
                help_text='[{"slot":1,"subjects_str":"ENG/KIS","min_grade":"C"}, ...]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="programme_code",
            field=models.CharField(
                blank=True, help_text="KUCCPS code e.g. 5000K32", max_length=20
            ),
        ),
    ]
