# Generated by Django 6.0.6 on 2026-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_add_kmtc_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="career_outcomes",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated example job titles e.g. Doctor, Surgeon, Physician",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(
                blank=True, help_text="e.g. 3 years, 18 months", max_length=60
            ),
        ),
    ]
