# Generated by Django 6.0.6 on 2026-06-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_review_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Editorial headline shown on homepage", max_length=200
                    ),
                ),
                ("summary", models.TextField(help_text="2-3 sentence editorial blurb")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_spotlights/"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotlights",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Spotlight",
                "verbose_name_plural": "Course Spotlights",
                "ordering": ["-start_date"],
            },
        ),
    ]
