# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0004_alter_subject_options_and_more"),
        ("courses", "0007_add_coursespotlight"),
        ("institutions", "0004_institutionpromotion_course_spotlight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_type"], name="courses_cou_course__320d41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["category"], name="courses_cou_categor_108713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecategory",
            index=models.Index(
                fields=["course_type"], name="courses_cou_course__c4d751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["institution"], name="courses_cou_institu_189c8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursespotlight",
            index=models.Index(
                fields=["start_date", "end_date"], name="courses_cou_start_d_934b63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["course", "rating"], name="courses_rev_course__b944e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["institution", "rating"], name="courses_rev_institu_fd50be_idx"
            ),
        ),
    ]
