# Generated by Django 5.2.15 on 2026-09-26 10:50

import kuccpss.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_courses_cou_course__320d41_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="course_pdfs/",
                validators=[kuccpss.upload_validators.SafePDFValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="coursespotlight",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="course_spotlights/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
    ]
