# Generated by Django 5.2.15 on 2026-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_pdf_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="entry_requirements",
            field=models.JSONField(
                blank=True,
                help_text='KUCCPS minimum entry requirements (the 4 cluster-subject slots): [{"slot":1,"subjects_str":"MAT A/MAT B/BST"}, ...]',
                null=True,
            ),
        ),
    ]
