# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_entry_requirements"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="courses_cou_slug_2e551f_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="courses_cou_course__320d41_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="courses_cou_categor_108713_idx",
        ),
        migrations.RemoveIndex(
            model_name="coursecategory",
            name="courses_cou_course__c4d751_idx",
        ),
        migrations.RemoveIndex(
            model_name="courseoffering",
            name="courses_cou_institu_189c8e_idx",
        ),
        migrations.RemoveIndex(
            model_name="coursetype",
            name="courses_cou_name_0f84b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="coursetype",
            name="courses_cou_slug_27f5fc_idx",
        ),
    ]
