"""
Seed Private TVET institutions from the TVETA accredited institutions register.
Source: https://www.tveta.go.ke/accredited-tvet-institutions/
Only "Registered and Licensed" institutions included (7 "Registered Only" excluded).
Run: conda run python manage.py seed_private_tvet
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from institutions.models import InstitutionType, Institution

# All 396 "Registered and Licensed" private TVET institutions from TVETA register.
# Format: (name, county/location)
PRIVATE_TVET_INSTITUTIONS = [
    ('MARENGONI COMMUNITY TECHNICAL COLLEGE', 'Kajiado'),
    ('MERCY COMMERCIAL VOCATIONAL TRAINING CENTRE', 'Kitui'),
    ('RAHMA LUMINOUS COLLEGE', 'Mombasa'),
    ('NAIROBI WEST COMPUTER COLLEGE', 'Migori'),
    ('Coastland Professional Training College', 'Mombasa'),
    ('Afritech Training Institute', 'Mombasa'),
    ('FRANCES TAYLOR VOCATIONAL TRAINING CENTER', 'Kitui'),
    ('BARAKA TECHNICAL COLLEGE', 'Machakos'),
    ('TEWA TRAINING CENTER', 'Kilifi'),
    ('CARENIC TRAINING COLLEGE - MAKUENI', 'Makueni'),
    ('WATULIZENI TECHNICAL TRAINING INSTITUTE', 'Kilifi'),
    ('Angaza Lucky Summer Vocational Training College', 'Nairobi'),
    ('Fanisi Technical Training College', 'Kiambu'),
    ('Mother Kevin Vocational Training Institute', 'Nakuru'),
    ('A-kili Vocational Training Centre-itigo', 'Nandi'),
    ('ST. ANNE MAWEGO YOUTH POLYTECHNIC', 'Homabay'),
    ('DON BOSCO TECHNICAL INSTITUTE - MARSABIT', 'Marsabit'),
    ('Leaders Training College-Eldoret', 'Uasin Gishu'),
    ('Mauche Vocational Training Institute', 'Nakuru'),
    ('Mwatate Christian Industrial Training Centre', 'Taita Taveta'),
    ('Mugunda Vocational Training Centre', 'Nyeri'),
    ('Vision Eden Vocational Training Centre', 'Kitui'),
    ('HOME OF ANGELS VOCATIONAL TRAINING CENTER', 'Kitui'),
    ('ADOK LIGEGA VOCATIONAL TRAINING CENTRE', 'Siaya'),
    ('South Eastern VTC-Kyambiti', 'Kitui'),
    ('Melbren Healthcare Training College', 'Kiambu'),
    ('NAGREGO TECHNICAL TRAINING COLLEGE', 'Kiambu'),
    ('Faith Victory Vocational Training Centre', 'Kitui'),
    ('YMCA VOCATIONAL TRAINING CENTER - KISUMU', 'Kisumu'),
    ('HELPING HAND SKILLS DEVELOPMENT CENTRE - NAIROBI', 'Nairobi'),
    ('Brighton vocational Training Center', 'Kilifi'),
    ('Cheni Training Institute', 'Nyeri'),
    ('MERCY CARE TRAINING CENTRE', 'Kiambu'),
    ('Ekerubo Technical Training Centre', 'Kisii'),
    ('Hacpad Vocational Training Centre', 'Mandera'),
    ('A.I.C DIGUNA RAINBOW POLYTECHNIC', 'Nandi'),
    ('NUU VOCATIONAL TRAINING CENTER', 'Kitui'),
    ('MWINGI MASTERY TECHNICAL COLLEGE', 'Kitui'),
    ('Tante African Studios Vocational Training Centre', 'Kiambu'),
    ('Coast Coffee Training Centre', 'Mombasa'),
    ('First Lady Computer Training College', 'Kilifi'),
    ('Kingdom Impartation Training Institute', 'Mombasa'),
    ('MAMA LORENZAS VOCATIONAL TRAINING CENTER', 'Kwale'),
    ('HARBOUR VIEW MARITIME TRAINING INSTITUTE', 'Kilifi'),
    ('Jenemos Hairdressing and Beauty College', 'Mombasa'),
    ('Matarajio Training Centre', 'Mandera'),
    ('ST KIZITO VOCATIONAL TRAINING INSTITUTE - GITHURAI', 'Kiambu'),
    ('LINGUA VOCATIONAL & TRAINING CENTER', 'Kwale'),
    ('Lvdiaspora Integration Language Training Institute', 'Mombasa'),
    ('Splash Coffee Barista Training Institute', 'Mombasa'),
    ('P.C.E.A KIBERA EMMANUEL TECHNICAL TRAINING CENTER', 'Nairobi'),
    ('SAN DAMIANO VOCATIONAL TRAINING CENTER', 'Machakos'),
    ('Mutech Training Institute', 'Kitui'),
    ('Velndale Vocational Training Centre', 'Nairobi'),
    ('Romesgate Training Institute', 'Mombasa'),
    ('St. Clare Vocational Training College', 'Nakuru'),
    ('ST. KIZITO VOCATIONAL TRAINING INSTITUTE - RUARAKA', 'Nairobi'),
    ('MERCY VOCATIONAL TRAINING CENTER', 'West Pokot'),
    ('MUKURU SKILLS TRAINING CENTER', 'Nairobi'),
    ('Taylored Training Institute', 'Kitui'),
    ('Coast Acumen Vocational Training Centre', 'Mombasa'),
    ('Helping Hand Skills Development Centre - Nyeri', 'Nyeri'),
    ('Teresia Van Miert Training Centre', 'Nairobi'),
    ('YMCA - NATIONAL TRAINING INSTITUTE', 'Nairobi'),
    ('ST. JOSEPHS VOCATIONAL TRAINING CENTER - MLOLONGO', 'Machakos'),
    ('PARIS COLLEGE OF HAIRDRESSING AND BEAUTY', 'Nairobi'),
    ('Procare Training Centre', 'Nairobi'),
    ('Maior Lugha School of International Languages', 'Nairobi'),
    ('Destiny Jayhan Technical Training College', 'Nakuru'),
    ('ANCILLA VOCATIONAL TRAINING CENTER', 'Mombasa'),
    ('Vessel of Hope Vocational Training Centre', 'Trans Nzoia'),
    ('Faith College of Fashion and Textiles', 'Turkana'),
    ('ST. KIZITO TRAINING CENTER UTAWALA', 'Nairobi'),
    ('International School of Advertising', 'Nairobi'),
    ('Sauti Kuu Resource and Training Centre', 'Siaya'),
    ('Latina Hair and Beauty College', 'Mombasa'),
    ('Ahero School of Health Sciences', 'Kisumu'),
    ('YARIS INSTITUTE OF INFORMATION AND BUSINESS STUDIES', 'Mombasa'),
    ('Barton Training Institute', 'Nairobi'),
    ('RARIEDA TRAINING AND RESOURCE CENTRE', 'Siaya'),
    ('TRIDENT VOCATIONAL TRAINING CENTER', 'Nairobi'),
    ('Goma Vocational Training Centre', 'Migori'),
    ('Hamburg International Training College', 'Uasin Gishu'),
    ('HELPING HAND SKILLS DEVELOPMENT CENTRE - LODWAR', 'Turkana'),
    ('Tender Touch Homecare Training Institute', 'Nairobi'),
    ('Helping Hand Skills Development Centre - Malindi', 'Kilifi'),
    ('ANCILLA VOCATIONAL TRAINING INSTITUTE', 'Uasin Gishu'),
    ('Trelyne Training Institute', 'Nairobi'),
    ('CHRISTIAN INDUSTRIAL TRAINING COLLEGE - THIKA', 'Kiambu'),
    ('FAFA MEDICAL TRAINING COLLEGE', 'Kakamega'),
    ('ACAI Institute of Technology', 'Nairobi'),
    ('Apostolic Faith Church Bible College', 'Nakuru'),
    ('Zuriel Technical Training Institute', 'Uasin Gishu'),
    ('AA Mobility and Road Safety Training Institute', 'Nairobi'),
    ('Abadyne Premier Technical Training Institute', 'Uasin Gishu'),
    ('DEEVA COLLEGE OF PROFESSIONAL STUDIES', 'Bungoma'),
    ('COMPUTER PRIDE TRAINING CENTRE', 'Nairobi'),
    ('ACK BISHOP HANNINGTON INSTITUTE OF THEOLOGY AND DEVELOPMENT STUDIES', 'Mombasa'),
    ('ST ELIZABETH SCHOOL OF NURSING MUKUMU', 'Kakamega'),
    ('GLORYCA INTERNATIONAL COLLEGE', 'Migori'),
    ('CAPACITY AND TRAINING INSTITUTE', 'Kakamega'),
    ('DOAN EDUCATION INSTITUTE', 'Nairobi'),
    ('Gocare Training Institute', 'Nairobi'),
    ('Ushindi College of Professional Studies', 'Nairobi'),
    ('Africa Institute of Health and Development, Kisumu', 'Kisumu'),
    ('ADVANCED CAREER TRAINING COLLEGE', 'Kitui'),
    ('Adia Training Centre', 'Nairobi'),
    ('ELDORET AVIATION TRAINING INSTITUTE', 'Uasin Gishu'),
    ('ADEPT COLLEGE OF PROFESSIONAL STUDIES', 'Nakuru'),
    ('MARIANIST TECHNICAL INSTITUTE - KWALE', 'Kwale'),
    ('EXCEL INSTITUTE OF PROFESSIONALS', 'Kiambu'),
    ('LIIT TECHNICAL COLLEGE', 'Kiambu'),
    ('Stanmore Training College', 'Nairobi'),
    ('African Christian Restoration Training Institute', 'Bungoma'),
    ('Amuaa Institute of Professional Studies', 'Kisumu'),
    ('Africa Mission Training Institute', 'Kitui'),
    ('ELDORET COLLEGE OF PROFESSIONAL STUDIES', 'Uasin Gishu'),
    ('AFRICAN MILLING SCHOOL', 'Kiambu'),
    ('MILESTONE INSTITUTE OF PROFESSIONAL STUDIES', 'Kiambu'),
    ("FRED'S RANCH SCHOOL OF HOSPITALITY", 'Kajiado'),
    ('African Pastoral Training Institute', 'Machakos'),
    ('Angaza Empowerment Training Center', 'Nairobi'),
    ('ELGON VIEW COLLEGE', 'Uasin Gishu'),
    ('CARLILE COLLEGE', 'Nairobi'),
    ('SHEARS AND NIPPERS SCHOOL OF HAIR AND BEAUTY', 'Nairobi'),
    ('KAPENGURIA INSTITUTE OF BUSINESS STUDIES AND TECHNOLOGY', 'West Pokot'),
    ('RIFKINS EDUCATION COLLEGE', 'Mombasa'),
    ('EQUIP AFRICA INSTITUTE - MALINDI CENTRE', 'Kilifi'),
    ('Alika Medical Training College', 'Kiambu'),
    ('Bureti Bible College', 'Kericho'),
    ('Amani Counselling Centre and Training Institute Nairobi CBD', 'Nairobi'),
    ('AMANI COUNSELING AND TRAINING INSTITUTE', 'Nairobi'),
    ('REGIONAL CURRICULUM MANAGEMENT COLLEGE', 'Nairobi'),
    ('Mulo College of Professional Studies', 'Samburu'),
    ('Somawise College', 'Kisii'),
    ('APMI Peace Missions Training Institute', 'Kajiado'),
    ('Aslead Training Institute', 'Machakos'),
    ('EXCEL GLOBAL COLLEGE', 'Nairobi'),
    ('DON BOSCO BOYS TECHNICAL TRAINING CENTRE', 'Nairobi'),
    ('TALANTA INSTITUTE', 'Nairobi'),
    ('Madonna Technical and Vocational College', 'Uasin Gishu'),
    ('Lindtech College', 'Nairobi'),
    ('Brickhouse Technical Training College', 'Kakamega'),
    ('Cakehearts International Hospitality Institute', 'Nairobi'),
    ('Aviation College of Kenya', 'Nairobi'),
    ('MACHAKOS INSTITUTE OF TECHNOLOGY', 'Machakos'),
    ("IMANI MARIANISTS 'CHAMINADE TRAINING CENTRE", 'Nairobi'),
    ('ELDORET TECHNICAL TRAINING INSTITUTE', 'Turkana'),
    ('Buruuj Training Institute', 'Kajiado'),
    ('Brooke Wood Institute of Professional Studies', 'Kiambu'),
    ('Candy College of Beauty and Applied Sciences', 'Kiambu'),
    ('Carey Beauty College', 'Nairobi'),
    ('IMANI MARIANISTS MARIA TRAINING CENTER', 'Nairobi'),
    ('BARTEK INSTITUTE - ELDAMA RAVINE CAMPUS', 'Baringo'),
    ('UNISON SCHOOL OF HAIRDRESSING AND BEAUTY', 'Kakamega'),
    ('Fleming Technical Institute', 'Kajiado'),
    ('NEP-MEWA College of Professional Studies', 'Mombasa'),
    ("Catholic Diocese Of Kakamega - St. Mary's Medical Training College", 'Kakamega'),
    ('Cawibo Technical Training College', 'Siaya'),
    ('Chania Medical Training College', 'Kiambu'),
    ('LUKENYA TRAINING INSTITUTE', 'Makueni'),
    ('BEAUTY POINT COLLEGE', 'Nairobi'),
    ('JAFFERY INSTITUTE OF PROFESSIONAL STUDIES', 'Mombasa'),
    ('VITECH TRAINING INSTITUTE', 'Siaya'),
    ('HALLMARK INSTITUTE OF PROFESSIONALS', 'Nairobi'),
    ('Nyamwange Technical Training Center', 'Nyamira'),
    ('Riara Business Training Institute', "Murang'a"),
    ('Climax Beauty College', 'Kiambu'),
    ('Citiscope Training Institute', 'Nairobi'),
    ('Crimbe Home Care and Training College', 'Mombasa'),
    ('MACHAKOS MEDICAL AND TECHNICAL TRAINING COLLEGE', 'Machakos'),
    ('JOAN SCHOOL OF NURSING', 'Kisumu'),
    ('EASTERN KENYA INTEGRATED COLLEGE - MITABONI', 'Machakos'),
    ('Libu Training Institute', 'Kiambu'),
    ('ICS Technical College - Eldoret', 'Uasin Gishu'),
    ('Clinifine Training Institute', 'Nairobi'),
    ('Grace Exquisite Skills and Technical College', 'Makueni'),
    ('BRIDGEWORLD COLLEGE', 'Nairobi'),
    ('ST. ANDREWS COLLEGE OF THEOLOGY AND DEVELOPMENT', 'Kirinyaga'),
    ('Sphereshine College', 'Makueni'),
    ('Turkana College of Technical and Business Studies - Kakuma Campus', 'Turkana'),
    ('Evolutionary Training Center', 'Nairobi'),
    ('Danid Training Institute', 'Kisumu'),
    ('Harvestime Institute of Biblical and Professional Studies', 'Nyandarua'),
    ('ELDORET A.I.C TRAINING COLLEGE', 'Uasin Gishu'),
    ('NYAMIRA INSTITUTE OF SCIENCE AND TECHNOLOGY', 'Kisii'),
    ('KENYA CHRISTIAN INDUSTRIAL TRAINING INSTITUTE', 'Nairobi'),
    ('KIBWEZI INSTITUTE OF PROFESSIONAL STUDIES', 'Makueni'),
    ('Vision Empowerment Training Institute', 'Kajiado'),
    ('Machoge Technical Training Institute', 'Kisii'),
    ('Fem Leadership College', 'Makueni'),
    ('Heniv Beauty College', 'Machakos'),
    ('KENYA INSTITUTE OF MANAGEMENT - NAROK BRANCH', 'Narok'),
    ('EQUIP AFRICA INSTITUTE - NAKURU CAMPUS', 'Nakuru'),
    ('GRATIA TECHNICAL TRAINING INSTITUTE', 'Kericho'),
    ('FULBRIGHT UNIVERSAL COLLEGE', 'Trans Nzoia'),
    ('Fooster Dairy Training Center', 'Nakuru'),
    ('Elmwood Healthcare Training Institute', 'Nairobi'),
    ('Institute of Human Resource Advancement Training College', 'Nairobi'),
    ('KENYA INSTITUTE OF DEVELOPMENT STUDIES - NAIROBI', 'Nairobi'),
    ('UWESO COLLEGE', 'Machakos'),
    ('CROSSROADS BIBLE INSTITUTE', 'Kilifi'),
    ('Pokot Technical and Vocational College', 'West Pokot'),
    ('Gates Africa Training Centre', 'Kisumu'),
    ('ELOW COLLEGE OF PROFESSIONAL STUDIES', 'Nairobi'),
    ('Jesus Harvesters Agape Bible College', 'West Pokot'),
    ('SHANG TAO MEDIA COLLEGE', 'Nairobi'),
    ('KABARAK UNIVERSITY TVET INSTITUTE', 'Nakuru'),
    ('MEMON COLLEGE', 'Mombasa'),
    ('Life Shape Technical Institute', 'Nakuru'),
    ('Home of Glory Technical and Vocational Training', 'Kisumu'),
    ('Etiba Training College', 'Nairobi'),
    ('Journey Christian Training Institute', 'Uasin Gishu'),
    ('ST JUDES TECHNICAL COLLEGE', 'Kakamega'),
    ('ISEBANIA TECHNICAL TRAINING COLLEGE', 'Migori'),
    ('Pamoja Technical Training College Nkubu', 'Meru'),
    ('Idia College of Technology and Development Studies', 'Kajiado'),
    ('EUNI Training Institute', 'Machakos'),
    ('ST. FRANCIS TECHNICAL TRAINING INSTITUTE - ASUMBI', 'Kisii'),
    ('EASTLANDS COLLEGE OF TECHNOLOGY', 'Nairobi'),
    ('KENYA INSTITUTE OF ORGANIC FARMING', 'Kiambu'),
    ('KENYA INSTITUTE OF PROFESSIONAL STUDIES (KIPS) - KPCU', 'Nairobi'),
    ('TROPICAL INSTITUTE OF COMMUNITY HEALTH AND DEVELOPMENT (TICH) IN AFRICA', 'Kisumu'),
    ('EYE RAFIKI TRAINING INSTITUTE', 'Uasin Gishu'),
    ('UJUZI YETU TECHNICAL AND VOCATIONAL INSTITUTE', 'Kwale'),
    ('Lizaya Training Institute of Cosmetology and Hospitality', 'Nairobi'),
    ('Impact training and counselling centre', 'Mombasa'),
    ('EVERLASTING TRAINING COLLEGE OF TECHNOLOGY STUDIES', 'Kitui'),
    ('Kyoani EAPC Technical and Vocational College', 'Kitui'),
    ('ST. JOHN PAUL II TRAINING INSTITUTE', 'Kitui'),
    ('PLASMA DIGITAL COLLEGE', 'Nairobi'),
    ('ORTUM MISSION HOSPITAL - SCHOOL OF NURSING', 'West Pokot'),
    ('EAGLE CREEK COLLEGE', 'Laikipia'),
    ('Brand Institute of Forensics and Security', 'Nairobi'),
    ('Infolink College of Technology', 'Nairobi'),
    ('Excelligent Health Training Institute', 'Nairobi'),
    ('Macmillan Medical Training College - City Campus', 'Nairobi'),
    ('VISION INSTITUTE OF PROFESSIONALS - NAIROBI', 'Nairobi'),
    ('SPAN INSTITUTE OF TECHNOLOGY', "Murang'a"),
    ('ST JOSEPH MISSION HOSPITAL SCHOOL OF NURSING', 'Migori'),
    ('SHILOH PROFESSIONAL COLLEGE', "Murang'a"),
    ('Ufahari Training Centre', 'Nairobi'),
    ('Integrated College of Professional Studies', 'Nairobi'),
    ('Fortis Medical Training College', 'Kirinyaga'),
    ('Macmillan Medical Training College - Mombasa', 'Mombasa'),
    ('CATHOLIC TECHNICAL TRAINING INSTITUTE - MACHAKOS', 'Machakos'),
    ('KIVULI COLLEGE', 'Kiambu'),
    ('KENAFRIC COLLEGE OF PROFESSIONAL STUDIES - NAIROBI', 'Nairobi'),
    ('Orthodox College of Africa', 'Nairobi'),
    ('Keborok Technical Training & Counselling Centre', 'Bomet'),
    ('Full Gospel Theology Training Institute', 'Nairobi'),
    ('Macmillan Medical Training College - Nakuru', 'Nakuru'),
    ('Wamachio Institute of Management and Innovation', 'Bungoma'),
    ('Kensal Beauty & Fashion College', 'Kisumu'),
    ('Malbag International Training College', 'Kajiado'),
    ('GOT MATAR INSTITUTE OF TECHNOLOGY', 'Siaya'),
    ('KRESTON MEDICAL TRAINING COLLEGE', 'Nairobi'),
    ('KIAMBU INSTITUTE OF BUSINESS STUDIES', 'Kiambu'),
    ('MOSORIOT TECHNICAL AND VOCATIONAL TRAINING INSTITUTE', 'Nandi'),
    ('Newton Institute of Technology', 'Migori'),
    ('Kenswed Technical and Vocational Training College', 'Kajiado'),
    ('International Jaamia of Languages and Professional Studies (IJLAPS)', 'Mombasa'),
    ('GREENWICH COLLEGE - GARISSA', 'Garissa'),
    ('LUSAKA INSTITUTE OF SCIENCE AND TECHNOLOGY', 'Narok'),
    ('EAST AFRICAN INSTITUTE OF HOMECARE MANAGEMENT', 'Kiambu'),
    ('MUMBUNI ENGINEERING AND DRIVING SCHOOL', 'Machakos'),
    ('WISETECH TRAINING INSTITUTE', 'Uasin Gishu'),
    ('Umma University TVET Institute', 'Kiambu'),
    ('Kibabii Technical Training Institute', 'Bungoma'),
    ('Jolearn Training College', 'Nairobi'),
    ('Masterline Training Institute', 'Nairobi'),
    ('MIGORI INSTITUTE OF SCIENCES AND TECHNOLOGY', 'Migori'),
    ('HEMLAND COLLEGE OF PROFESSIONAL AND TECHNICAL STUDIES - THIKA ARCADE', 'Kiambu'),
    ('NAIROBI COLLEGE OF BREAD AND CONFECTIONERY TECHNOLOGY - MOMBASA', 'Mombasa'),
    ('KENYA COLLEGE OF INTERIOR DESIGN', 'Nairobi'),
    ('Compliance Institute of Professional studies', 'Kajiado'),
    ('Kimlea Hospitality Training College', 'Kiambu'),
    ('King David Leadership Institute', 'Nairobi'),
    ('Newbirth Professional Institute', 'Nyandarua'),
    ('INTERNATIONAL HOTEL AND TOURISM INSTITUTE', 'Nairobi'),
    ('Qubit Institute of Technology', 'Machakos'),
    ('Kipsigis Institute of Vocational Training College', 'Kericho'),
    ('Lakewise Technical Training Institute', 'Kisumu'),
    ('Nextbridge Institute of Professional Studies', 'Kajiado'),
    ('INTERNATIONAL CENTRE OF TECHNOLOGY', 'Kiambu'),
    ('SKYWORLD AVIATION TRAINING COLLEGE', 'Nairobi'),
    ('BISHOP LOCATI TECHNICAL TRAINING INSTITUTE - ISIOLO', 'Isiolo'),
    ('Zurie Beauty Palour College-Kayole Junction', 'Nairobi'),
    ('Kisii Impact Institute of Science and Technology', 'Kisii'),
    ('LEONARD FOX THEOLOGY TRAINING COLLEGE', 'Kiambu'),
    ('Nexus Institute of Professional Studies', 'Nakuru'),
    ('JODAN COLLEGE OF TECHNOLOGY - THIKA', 'Kiambu'),
    ('KCA UNIVERSITY PROFESSIONAL AND TECHNICAL TRAINING INSTITUTE', 'Nairobi'),
    ('ARCHDIOCESE OF NAIROBI KARIOBANGI WOMEN PROMOTION TRAINING INSTITUTE', 'Nairobi'),
    ('AUSCARE INTERNATIONAL COLLEGE', 'Mombasa'),
    ('Yan School of Hospitality', 'Nairobi'),
    ('Knowledge Spring Training Institute', 'Uasin Gishu'),
    ('Lintons College of Beauty - Mombasa', 'Mombasa'),
    ('Rainedge International Training College', 'Nakuru'),
    ('MARIANIST TECHNICAL INSTITUTE - MOMBASA', 'Mombasa'),
    ('JEWEL PROFESSIONAL COLLEGE', 'Nairobi'),
    ('GERMAINE TRAINING INSTITUTE', 'Nakuru'),
    ('FR. FRANCIS XAVIER CATHOLIC INSTITUTE', 'Kilifi'),
    ('Centurion Training Institute of Tourism and Hospitality', 'Nairobi'),
    ('Mannara Institute of Aviation and Professional Studies', 'Nairobi'),
    ('Marura Technical Training Institute', 'Nairobi'),
    ('RCM Online College', 'Nairobi'),
    ('MATIBABU FOUNDATION COLLEGE OF HEALTH SCIENCES', 'Siaya'),
    ('SEVERIN CRAFTSMAN TRAINING CENTRE', 'Mombasa'),
    ('NAIROBI COLLEGE OF BREAD - Nakuru', 'Nakuru'),
    ('ELDOSTAR COLLEGE', 'Uasin Gishu'),
    ('Kisasa Technical Training Institute', 'Nakuru'),
    ('Medlutek International College of Health Sciences', 'Nairobi'),
    ('Maximilian College of Professional Studies', 'Nakuru'),
    ('Sanfields Business and Technology Training Institute', 'Kirinyaga'),
    ('KENYA INSTITUTE OF BUSINESS AND COUNSELING STUDIES', 'Nairobi'),
    ('FINSTOCK EVARSITY COLLEGE', 'Nairobi'),
    ('CAMBRIDGE UNIVERSAL COLLEGE', 'Uasin Gishu'),
    ('IMPERIAL COLLEGE OF MEDICAL AND HEALTH SCIENCES', 'Kiambu'),
    ('NEHEMA INSTITUTE OF SCIENCE AND TECHNOLOGY', 'Uasin Gishu'),
    ('Theophilus Theological Institute', 'Kiambu'),
    ('Medprime Training College', 'Nairobi'),
    ('Mediacrest Training College', 'Nairobi'),
    ('Bonicare Training Institute', 'Embu'),
    ('MOMBASA AVIATION TRAINING INSTITUTE', 'Mombasa'),
    ("GERTRUDE'S INSTITUTE OF CHILD HEALTH AND RESEARCH", 'Nairobi'),
    ('VERA TECHNICAL TRAINING COLLEGE', 'Nakuru'),
    ('RAVINE BIBLE COLLEGE AND THEOLOGICAL SEMINARY', 'Baringo'),
    ('Imani Digital Learning Centre (IDLC)', 'Trans Nzoia'),
    ('Mediplus Training Institute', 'Uasin Gishu'),
    ('Scott Christian University TVET Institute', 'Machakos'),
    ('MWANGAZA COLLEGE - NAKURU', 'Nakuru'),
    ('KENYA SCHOOL OF MEDICAL SCIENCE AND TECHNOLOGY', 'Kiambu'),
    ('ELGON VIEW COLLEGE - KISII', 'Kisii'),
    ('INTRAGLOBAL TRAINING INSTITUTE', 'Nairobi'),
    ('TASK CATERING TRAINING INSTITUTE', 'Nairobi'),
    ('Minto Institute of Professional Studies', 'Nyamira'),
    ('Menorah Training Institute', 'Mombasa'),
    ('St. Michaels Leadership Vocational Training Institute', 'Kajiado'),
    ('NAIROBI AVIATION COLLEGE - KISUMU', 'Kisumu'),
    ('MILELE COLLEGE NAKURU', 'Nakuru'),
    ('EQUIP AFRICA INSTITUTE - THIKA CENTER', 'Kiambu'),
    ('TOPMAX TRAINING COLLEGE', 'Nairobi'),
    ('THIKA COLLEGE OF EXCELLENCE', 'Kiambu'),
    ('Kairo College of Leadership and Hospitality', 'Kiambu'),
    ('Nairobi Institute of Medical and Emergency Training', 'Nairobi'),
    ('Mercylife college', 'Kiambu'),
    ('Starehe Technical Training College', 'Kiambu'),
    ('KILIFI COLLEGE OF ACCOUNTANCY', 'Kilifi'),
    ('MOMBASA AIRWAYS TRAINING INSTITUTE', 'Mombasa'),
    ('NAIROBI PLATINUM COLLEGE', 'Nairobi'),
    ('BUMULA INSTITUTE OF HEALTH AND DEVELOPMENT', 'Bungoma'),
    ('THE NAIROBI WEST HOSPITAL COLLEGE OF HEALTH SCIENCES', 'Nairobi'),
    ('Nairobi South Training Institute', 'Kajiado'),
    ('MWATATE MEDICAL TRAINING INSTITUTE', 'Taita Taveta'),
    ('Starwan Technical Institute', 'Kiambu'),
    ('KINGS COLLEGE OF ACCOUNTANCY', 'Uasin Gishu'),
    ('KENYA INSTITUTE OF MANAGEMENT THIKA BRANCH', 'Kiambu'),
    ('INSTITUTE OF ADVANCED TECHNOLOGY - MOMBASA', 'Mombasa'),
    ('MWEMBENI TECHNICAL TRAINING INSTITUTE', 'Kilifi'),
    ('Atesh Graphics Media College', 'Nakuru'),
    ('North Rift Christian College', 'Trans Nzoia'),
    ('Techsavanna Software Institute', 'Nairobi'),
    ('AFRICA DIGITAL MEDIA INSTITUTE', 'Nairobi'),
    ('ANNICKS FOR KENYA TAILORING COLLEGE', 'Kwale'),
    ('BURUBURU INSTITUTE OF FINE ARTS', 'Nairobi'),
    ('Visualdo Institute', 'Nairobi'),
    ('Optident Dental and Technical and Institute', 'Embu'),
    ("Nyahururu Diocese St. Ann's Catholic Training Institute", 'Laikipia'),
    ('Thika Talents Technical College', 'Kiambu'),
    ('CATHERINE MCAULEY NURSING SCHOOL - MATER HOSPITAL', 'Nairobi'),
    ('ST JOHN PAUL II INSTITUTE SCHOOL OF ENGINEERING', 'Kitui'),
    ('Stedmak Hospitality Training College - Rongai Campus', 'Kajiado'),
    ('Petrimore Institute of Medical and Health Sciences', 'Laikipia'),
    ('Oakwood Training Institute', 'Kiambu'),
    ('Vanguard Technical and Counselling Training Institute', 'Nairobi'),
    ('CHRISTIAN INDUSTRIAL TRAINING CENTRE - NAIROBI', 'Nairobi'),
    ('GARISSA COMMERCIAL COLLEGE', 'Garissa'),
    ('ST. CAMILLUS COLLEGE OF NURSING', 'Kisii'),
    ('FIDENZA SCHOOL OF NURSING', 'Embu'),
    ('SPRING OF HOPE RIVERSIDE COLLEGE', 'Bomet'),
    ('St. Dominics Technical and Agricultural Training Institute', 'Kiambu'),
    ('Radiance Training Institute', 'Kiambu'),
    ('Pine Hospital Training Institute', 'Nyandarua'),
    ('Apostles of Jesus Major Seminary', 'Nairobi'),
    ('LIONS INSTITUTE OF TECHNOLOGIES', 'Nakuru'),
    ('Brighter Minds Technical and Vocational College', 'Kiambu'),
    ('Skyview International Technical Training Institute', 'Kiambu'),
    ('La Contessa International Training College', 'Nairobi'),
    ('COLLEGE OF HUMAN RESOURCE MANAGEMENT', 'Nairobi'),
    ('RAM TRAINING COLLEGE', 'Kisii'),
    ('NYAHURURU MEDICAL TRAINING INSTITUTE', 'Nyandarua'),
    ('MARSHILL TECHNICAL AND VOCATIONAL CENTRE', 'Tharaka Nithi'),
    ('BRIGHTER COLLEGE', 'Kajiado'),
    ('Luddoc Skills for Life Technical Institute', 'Kiambu'),
    ('St Mulumba TVC', 'Mombasa'),
]


class Command(BaseCommand):
    help = 'Seed Private TVET institutions from the TVETA accredited register'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Remove existing Private TVET institutions before seeding',
        )

    def handle(self, *args, **options):
        with transaction.atomic():
            priv_type, _ = InstitutionType.objects.get_or_create(
                name='Private TVET',
                defaults={
                    'description': 'TVETA-accredited and licensed private TVET institutions.',
                    'icon': 'fas fa-tools',
                    'color_code': '#7c3aed',
                },
            )

            if options['clear']:
                deleted, _ = Institution.objects.filter(institution_type=priv_type).delete()
                self.stdout.write(self.style.WARNING(f'Cleared {deleted} existing Private TVET institutions'))

            created = 0
            updated = 0
            for name, location in PRIVATE_TVET_INSTITUTIONS:
                inst, was_created = Institution.objects.get_or_create(
                    name=name,
                    defaults={
                        'institution_type': priv_type,
                        'location': location,
                    },
                )
                if was_created:
                    created += 1
                else:
                    # Update type and location if institution exists under old type
                    changed = False
                    if inst.institution_type != priv_type:
                        inst.institution_type = priv_type
                        changed = True
                    if not inst.location and location:
                        inst.location = location
                        changed = True
                    if changed:
                        inst.save(update_fields=['institution_type', 'location'])
                        updated += 1

        total = Institution.objects.filter(institution_type=priv_type).count()
        self.stdout.write(self.style.SUCCESS(
            f'Done. Created: {created}, Updated: {updated}. '
            f'Total Private TVET institutions: {total}'
        ))
