# Generated by Django 5.2.8 on 2026-03-06 15:50

import career.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KCSEGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='KMTCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TTCCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVETCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommended_fields', models.TextField(blank=True, null=True)),
                ('career_paths', models.TextField(blank=True, null=True)),
                ('cluster_subjects', models.ManyToManyField(blank=True, to='career.clustersubject')),
                ('category', models.ForeignKey(default=career.models.get_default_course_category, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='career.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='KMTCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('min_mean_grade', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('career_paths', models.TextField(blank=True, null=True)),
                ('campuses', models.ManyToManyField(blank=True, to='career.kmtcampus')),
                ('required_subjects', models.ManyToManyField(blank=True, to='career.clustersubject')),
            ],
        ),
        migrations.CreateModel(
            name='TTCCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('min_mean_grade', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('career_paths', models.TextField(blank=True, null=True)),
                ('colleges', models.ManyToManyField(blank=True, to='career.ttccollege')),
                ('required_subjects', models.ManyToManyField(blank=True, to='career.clustersubject')),
            ],
        ),
        migrations.CreateModel(
            name='TVETCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('min_mean_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('career_paths', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvet_courses', to='career.tvetcategory')),
                ('required_subjects', models.ManyToManyField(blank=True, to='career.clustersubject')),
            ],
        ),
        migrations.CreateModel(
            name='CareerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_level', models.CharField(blank=True, max_length=50, null=True)),
                ('average_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('career_fields', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to='career.course')),
                ('kmc_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to='career.kmtcourse')),
                ('ttc_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to='career.ttccourse')),
                ('tvet_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to='career.tvetcourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_chance', models.CharField(blank=True, max_length=50, null=True)),
                ('match_score', models.FloatField(default=0)),
                ('recommended_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.course')),
                ('kmc_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.kmtcourse')),
                ('ttc_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.ttccourse')),
                ('tvet_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.tvetcourse')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.university')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCutoffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('cutoff_points', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_history', to='career.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_history', to='career.university')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_points', models.FloatField()),
                ('year', models.PositiveIntegerField(default=2026)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='career.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='career.university')),
            ],
        ),
    ]
