# Generated by Django 6.0.6 on 2026-06-10 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interest", "Interests"),
                            ("strength", "Strengths"),
                            ("personality", "Personality"),
                            ("values", "Values"),
                        ],
                        default="interest",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("description", models.TextField()),
                (
                    "duties",
                    models.TextField(
                        blank=True, help_text="Key duties and responsibilities"
                    ),
                ),
                (
                    "skills_required",
                    models.TextField(
                        blank=True, help_text="Skills needed for this career"
                    ),
                ),
                (
                    "educational_pathway",
                    models.TextField(
                        blank=True, help_text="Steps to enter this career"
                    ),
                ),
                (
                    "job_opportunities",
                    models.TextField(blank=True, help_text="Where you can work"),
                ),
                (
                    "average_salary",
                    models.CharField(
                        blank=True,
                        help_text="e.g. KSh 50,000 – 150,000/month",
                        max_length=100,
                    ),
                ),
                (
                    "demand_level",
                    models.CharField(
                        choices=[
                            ("very_high", "Very High"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "future_outlook",
                    models.TextField(blank=True, help_text="Future growth prospects"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon class", max_length=50
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="career_profile_images/"
                    ),
                ),
                (
                    "career_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags used for quiz matching, e.g. science,health,biology",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_courses",
                    models.ManyToManyField(
                        blank=True, related_name="career_profiles", to="courses.course"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "career_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated career tags this option maps to, e.g. science,engineering",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="career.quizquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career.quizoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career.quizquestion",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="career.quizsubmission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "question")},
            },
        ),
    ]
