# Generated by Django 6.0.6 on 2026-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0005_careerconfig_competitive_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="ai_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Turn the AI Career Insight box on the quiz results page on or off.",
            ),
        ),
        migrations.AddField(
            model_name="careerconfig",
            name="ai_prompt_template",
            field=models.TextField(
                blank=True,
                help_text="Prompt sent to GPT-4o-mini. Use {tag_str} for interest tags and {careers_str} for matched careers. Leave blank to use the default prompt.",
            ),
        ),
        migrations.AlterField(
            model_name="careerconfig",
            name="safe_max_diff",
            field=models.FloatField(
                default=8.0,
                help_text="Max points above cutoff for 'Safe Option'. Beyond this becomes 'Easy Admission'. E.g. 8.0 means diff 3–8 = Safe.",
            ),
        ),
        migrations.AlterField(
            model_name="careerconfig",
            name="stretch_min_diff",
            field=models.FloatField(
                default=-3.0,
                help_text="Min points BELOW cutoff still counted as 'Stretch Opportunity' (enter as negative). E.g. -3.0 means student can be up to 3 pts below cutoff and still see it as Stretch.",
            ),
        ),
    ]
