# Generated by Django 6.0.6 on 2026-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0008_aiknowledgeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("career_name", models.CharField(max_length=150, unique=True)),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated lowercase terms matched against course career_outcomes (e.g. doctor,physician,surgeon)",
                        max_length=600,
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        help_text="Monthly gross KES — lower end"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        help_text="Monthly gross KES — upper end"
                    ),
                ),
                (
                    "demand",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                (
                    "top_sectors",
                    models.CharField(
                        help_text="Comma-separated hiring sectors", max_length=300
                    ),
                ),
                ("source_year", models.PositiveSmallIntegerField(default=2024)),
                (
                    "source_name",
                    models.CharField(
                        default="BrighterMonday Kenya Salary Report 2024",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, default="https://www.brightermonday.co.ke/research"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Market Data",
                "verbose_name_plural": "Job Market Data",
                "ordering": ["career_name"],
            },
        ),
        migrations.AlterField(
            model_name="aiknowledgeentry",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated search words (e.g. c+,degree,university,qualify)",
                max_length=500,
            ),
        ),
    ]
