# Generated by Django 6.0.6 on 2026-06-21 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0009_job_market_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="ai_daily_limit",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum number of AI calls (chat + insight) a single user or session may make per calendar day. Set to 0 to disable rate limiting entirely.",
            ),
        ),
        migrations.CreateModel(
            name="AICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("date", models.DateField(db_index=True)),
                ("call_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Call Log",
                "verbose_name_plural": "AI Call Logs",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "date"),
                        name="unique_user_date_ai_log",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("session_key", "date"),
                        name="unique_session_date_ai_log",
                    ),
                ],
            },
        ),
    ]
