# Generated by Django 6.0.6 on 2026-06-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0010_ai_call_log_and_daily_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="ai_chat_max_messages",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Maximum number of messages a user can send in a single chat conversation. Set to 0 for unlimited. Ignored when rate limiting is disabled.",
            ),
        ),
        migrations.AddField(
            model_name="careerconfig",
            name="rate_limiting_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable rate limiting entirely. When off, users can make unlimited AI calls regardless of the limits below.",
            ),
        ),
        migrations.AlterField(
            model_name="careerconfig",
            name="ai_daily_limit",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum total AI calls (chat messages + insight requests) per user/session per calendar day. Ignored when rate limiting is disabled.",
            ),
        ),
        migrations.AlterField(
            model_name="careerconfig",
            name="ai_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch — disables ALL AI features site-wide (chat, insight, quiz summary). Use this to cut off OpenAI calls instantly without touching code.",
            ),
        ),
        migrations.AlterField(
            model_name="careerconfig",
            name="ai_prompt_template",
            field=models.TextField(
                blank=True,
                help_text="Prompt sent to GPT-4o-mini for the quiz results summary. Use {tag_str} for interest tags and {careers_str} for matched careers. Leave blank to use the default prompt.",
            ),
        ),
    ]
