# Generated by Django 6.0.6 on 2026-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0011_rate_limiting_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="tawk_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show or hide the Tawk.to live chat widget on the dashboard. Disable this to remove the widget without touching code.",
            ),
        ),
    ]
