# Generated by Django 6.0.6 on 2026-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0012_add_tawk_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="mentor_signup_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show or hide the 'Become a Mentor' button and signup page. Disable to pause new mentor applications without removing existing mentors.",
            ),
        ),
    ]
