# Generated by Django 6.0.6 on 2026-06-21 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0013_add_mentor_signup_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionLockConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("degree_career", "Career Engine (Degree Path)"),
                            ("cluster_calculator", "Cluster Points Calculator"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "lock_minutes",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Minutes the user has to review and edit before their submission is locked.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to allow unlimited resubmission (no locking).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Lock Config",
                "verbose_name_plural": "Submission Lock Configs",
            },
        ),
        migrations.CreateModel(
            name="CareerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("degree_career", "Career Engine (Degree Path)"),
                            ("cluster_calculator", "Cluster Points Calculator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grades_json",
                    models.JSONField(help_text="Saved as {subject_name: points_int}."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — editable"),
                            ("locked", "Locked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "lock_at",
                    models.DateTimeField(
                        help_text="Submission auto-locks after this time."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Submission",
                "verbose_name_plural": "Career Submissions",
                "unique_together": {("user", "feature")},
            },
        ),
    ]
