# Generated by Django 6.0.6 on 2026-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0014_submission_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="careersubmission",
            name="method",
            field=models.CharField(
                choices=[
                    ("calculate", "Calculator (estimated)"),
                    ("upload", "Upload KCSE slip"),
                    ("paste", "Paste cluster points"),
                    ("manual", "Manual cluster points entry"),
                ],
                default="calculate",
                help_text="Which entry method the student used.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submissionlockconfig",
            name="allow_official_resubmit",
            field=models.BooleanField(
                default=False,
                help_text="When ON: users who submitted via the calculator can resubmit once more using Upload / Paste / Manual (for when real KUCCPS cluster points are released). The calculator itself stays blocked.",
            ),
        ),
        migrations.AlterField(
            model_name="careersubmission",
            name="grades_json",
            field=models.JSONField(
                help_text="Subject grades {name: points} for calculate/upload; cluster points {num: pts} for paste/manual."
            ),
        ),
    ]
