# Generated by Django 6.0.6 on 2026-06-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0015_submission_method_and_resubmit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="ai_free_message_limit",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Total lifetime free AI chat messages a registered user gets before hitting the paywall. E.g. 20 means the first 20 messages are free forever.",
            ),
        ),
        migrations.AddField(
            model_name="careerconfig",
            name="ai_paid_message_limit",
            field=models.PositiveIntegerField(
                default=200,
                help_text="Number of AI chat messages unlocked each time a user makes a payment. E.g. 200 means each top-up gives 200 additional messages.",
            ),
        ),
        migrations.AlterField(
            model_name="careerconfig",
            name="ai_daily_limit",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Daily AI call limit for ANONYMOUS (non-logged-in) users only. Logged-in users are governed by ai_free_message_limit instead.",
            ),
        ),
        migrations.CreateModel(
            name="AIChatCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_messages_used", models.PositiveIntegerField(default=0)),
                ("paid_messages_remaining", models.PositiveIntegerField(default=0)),
                ("total_paid_ever", models.PositiveIntegerField(default=0)),
                ("last_topped_up_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_credit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Credit",
                "verbose_name_plural": "AI Chat Credits",
            },
        ),
    ]
