# Generated by Django 6.0.6 on 2026-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0016_ai_chat_credit_and_config_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichatcredit",
            name="free_period_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the current free-message period. Updated each time the counter is auto-reset.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="careerconfig",
            name="ai_free_reset_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Days before the free message counter resets automatically for users who haven't paid. E.g. 1 = resets every day, 7 = every week. 0 = never reset (lifetime allocation — user must pay once exhausted).",
            ),
        ),
    ]
