# Generated by Django 6.0.6 on 2026-06-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0018_airecommendation_user_studentcoursematch_user"),
        ("clusters", "0004_alter_subject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="KUCCPS cluster this course belongs to — used for the slot-based cluster points formula",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="career_courses",
                to="clusters.cluster",
            ),
        ),
    ]
