# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0019_add_cluster_fk_to_course"),
        ("courses", "0007_add_coursespotlight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursecutoff",
            unique_together={("course", "university", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="coursecutoffhistory",
            unique_together={("course", "university", "year")},
        ),
        migrations.AddIndex(
            model_name="aicalllog",
            index=models.Index(
                fields=["user", "date"], name="career_aica_user_id_34957f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiknowledgeentry",
            index=models.Index(
                fields=["is_active", "category"], name="career_aikn_is_acti_4e52b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(
                fields=["user", "created_at"], name="career_aire_user_id_3ec0d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careerprofile",
            index=models.Index(fields=["slug"], name="career_care_slug_d2e264_idx"),
        ),
        migrations.AddIndex(
            model_name="careerprofile",
            index=models.Index(
                fields=["demand_level"], name="career_care_demand__52eedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careersubmission",
            index=models.Index(fields=["status"], name="career_care_status_c0a14f_idx"),
        ),
        migrations.AddIndex(
            model_name="careersubmission",
            index=models.Index(
                fields=["lock_at"], name="career_care_lock_at_d56286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecutoff",
            index=models.Index(fields=["year"], name="career_cour_year_d7dab5_idx"),
        ),
        migrations.AddIndex(
            model_name="coursecutoffhistory",
            index=models.Index(fields=["year"], name="career_cour_year_2a7a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="sharedresult",
            index=models.Index(fields=["user"], name="career_shar_user_id_30982f_idx"),
        ),
        migrations.AddIndex(
            model_name="sharedresult",
            index=models.Index(
                fields=["expires_at"], name="career_shar_expires_8c436f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentcoursematch",
            index=models.Index(
                fields=["user", "created_at"], name="career_stud_user_id_6c8674_idx"
            ),
        ),
    ]
