# Generated by Django 6.0.6 on 2026-06-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0020_alter_coursecutoff_unique_together_and_more"),
        ("payments", "0009_payment_payments_pa_user_id_407fec_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="careersubmission",
            name="unlocked_by_payment",
            field=models.ForeignKey(
                blank=True,
                help_text="The payment that locked and unlocked viewing for this grade session.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_submissions",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="submissionlockconfig",
            name="lock_on_payment",
            field=models.BooleanField(
                default=True,
                help_text="When ON: grades are locked immediately when the linked payment completes (view_cluster_points → cluster_calculator; premium_career_report → degree_career). Turn OFF to rely only on the time-based grace period.",
            ),
        ),
    ]
