# Generated by Django 6.0.6 on 2026-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0021_submissionlock_lock_on_payment_unlocked_by_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerconfig",
            name="ai_model_name",
            field=models.CharField(
                default="gpt-4o-mini",
                help_text="OpenAI model used for all CareerNext AI features (chat, insight, quiz summary). Change this to switch models without a code deploy, e.g. 'gpt-4o' or 'gpt-4o-mini'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="careerconfig",
            name="ai_temperature",
            field=models.FloatField(
                default=0.6,
                help_text="Sampling temperature (0.0–2.0) applied to all CareerNext AI calls. Lower = more focused/deterministic, higher = more creative/varied.",
            ),
        ),
    ]
