# Generated by Django 5.2.15 on 2026-09-26 10:50

import kuccpss.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0022_careerconfig_ai_model_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="career_profile_images/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
    ]
