# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0023_alter_careerprofile_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="careerprofile",
            name="career_care_slug_d2e264_idx",
        ),
        migrations.RemoveIndex(
            model_name="sharedresult",
            name="career_shar_user_id_30982f_idx",
        ),
    ]
