# Generated by Django 5.2.15 on 2026-10-04 21:28

from django.db import migrations, models


def seed_non_degree_lock(apps, schema_editor):
    """Mirror the degree lock's grace period so non-degree pathways lock the same way."""
    Config = apps.get_model("career", "SubmissionLockConfig")
    degree = Config.objects.filter(feature="degree_career").first()
    Config.objects.get_or_create(
        feature="non_degree_career",
        defaults={
            "lock_minutes": degree.lock_minutes if degree else 2,
            "is_enabled": degree.is_enabled if degree else True,
            "lock_on_payment": degree.lock_on_payment if degree else True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0024_db_index_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersubmission",
            name="feature",
            field=models.CharField(
                choices=[
                    ("degree_career", "Career Engine (Degree Path)"),
                    ("cluster_calculator", "Cluster Points Calculator"),
                    (
                        "non_degree_career",
                        "Career Engine (Diploma / Certificate / KMTC / TTC / Artisan)",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="submissionlockconfig",
            name="feature",
            field=models.CharField(
                choices=[
                    ("degree_career", "Career Engine (Degree Path)"),
                    ("cluster_calculator", "Cluster Points Calculator"),
                    (
                        "non_degree_career",
                        "Career Engine (Diploma / Certificate / KMTC / TTC / Artisan)",
                    ),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="submissionlockconfig",
            name="lock_on_payment",
            field=models.BooleanField(
                default=True,
                help_text="When ON: grades are locked immediately when the linked payment completes (view_cluster_points → cluster_calculator; premium_career_report → degree_career and non_degree_career). Turn OFF to rely only on the time-based grace period.",
            ),
        ),
        migrations.RunPython(seed_non_degree_lock, migrations.RunPython.noop),
    ]
