# Generated by Django 5.2.8 on 2026-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the cluster, e.g., Cluster A', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the cluster')),
                ('color_code', models.CharField(blank=True, help_text='Optional hex color code for dashboard cards, e.g., #FF5733', max_length=7, null=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for UI (FontAwesome or similar)', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional image representing this cluster', null=True, upload_to='cluster_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clusters_cl_name_e2a544_idx'), models.Index(fields=['slug'], name='clusters_cl_slug_e7d66b_idx')],
            },
        ),
    ]
