# Generated by Django 5.2.8 on 2026-02-28 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional subject code (for future integration)', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True, help_text='If True, best subject from this group must be included')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower number = higher priority')),
            ],
            options={
                'verbose_name': 'Subject Group',
                'verbose_name_plural': 'Subject Groups',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['number', 'name'], 'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AddField(
            model_name='cluster',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Cluster number (used for ordering or official identification)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cluster_images/'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(help_text='Example: Education, Engineering, Health Sciences', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['number'], name='clusters_cl_number_16f5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='clusters_su_name_6efa29_idx'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='clusters.cluster'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subjects',
            field=models.ManyToManyField(related_name='subject_groups', to='clusters.subject'),
        ),
        migrations.AddIndex(
            model_name='subjectgroup',
            index=models.Index(fields=['priority'], name='clusters_su_priorit_f9f06a_idx'),
        ),
    ]
