# Generated by Django 6.0.6 on 2026-06-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0003_subject_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["group", "name"],
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.RenameIndex(
            model_name="subject",
            new_name="clusters_su_group_08801d_idx",
            old_name="clusters_su_group_idx",
        ),
    ]
