# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0005_alter_cluster_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cluster",
            name="clusters_cl_name_e2a544_idx",
        ),
        migrations.RemoveIndex(
            model_name="cluster",
            name="clusters_cl_slug_e7d66b_idx",
        ),
        migrations.RemoveIndex(
            model_name="cluster",
            name="clusters_cl_number_16f5d4_idx",
        ),
        migrations.RemoveIndex(
            model_name="subject",
            name="clusters_su_name_6efa29_idx",
        ),
    ]
