# Generated by Django 5.2.8 on 2026-03-01 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cluster_images/')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=2, unique=True)),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_language', models.BooleanField(default=False)),
                ('is_science', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='clusterpoints.cluster')),
                ('subjects', models.ManyToManyField(related_name='subject_groups', to='clusterpoints.subject')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='UserKCSEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mean_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('total_points', models.PositiveIntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusterpoints.subject')),
                ('kcse_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='clusterpoints.userkcseresult')),
            ],
            options={
                'ordering': ['subject__name'],
                'unique_together': {('kcse_result', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ClusterCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_points', models.FloatField(default=0, editable=False)),
                ('core_subject_total', models.PositiveIntegerField(default=0, editable=False)),
                ('aggregate_total', models.PositiveIntegerField(default=0, editable=False)),
                ('weighted_calculation', models.FloatField(default=0, editable=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusterpoints.cluster')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects_used', models.ManyToManyField(blank=True, related_name='used_in_cluster_results', to='clusterpoints.subject')),
                ('kcse_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_results', to='clusterpoints.userkcseresult')),
            ],
            options={
                'ordering': ['cluster__number'],
                'unique_together': {('user', 'kcse_result', 'cluster')},
            },
        ),
    ]
