# Generated by Django 5.2.8 on 2026-03-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterpoints', '0001_initial'),
        ('clusters', '0002_subject_subjectgroup_alter_cluster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustercalculationresult',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='clusters.cluster'),
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.subject'),
        ),
        migrations.AlterField(
            model_name='clustercalculationresult',
            name='subjects_used',
            field=models.ManyToManyField(blank=True, related_name='used_in_cluster_results', to='clusters.subject'),
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='SubjectGroup',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
