# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusterpoints", "0002_alter_clustercalculationresult_cluster_and_more"),
        ("clusters", "0004_alter_subject_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clustercalculationresult",
            index=models.Index(
                fields=["user", "cluster"], name="clusterpoin_user_id_c91cb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustercalculationresult",
            index=models.Index(
                fields=["kcse_result"], name="clusterpoin_kcse_re_49cb84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userkcseresult",
            index=models.Index(
                fields=["user", "created_at"], name="clusterpoin_user_id_f6487f_idx"
            ),
        ),
    ]
