# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "clusterpoints",
            "0003_clustercalculationresult_clusterpoin_user_id_c91cb5_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clustercalculationresult",
            name="clusterpoin_kcse_re_49cb84_idx",
        ),
    ]
