# Generated by Django 5.2.8 on 2026-02-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon for UI cards', max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Hex color for UI display', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Institution Type',
                'verbose_name_plural': 'Institution Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='institution_name_c8a941_idx'), models.Index(fields=['slug'], name='institution_slug_1b23ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='City, County, etc.', max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF brochure or requirements', null=True, upload_to='institution_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='institutions.institutiontype')),
            ],
            options={
                'ordering': ['institution_type', 'name'],
                'indexes': [models.Index(fields=['name'], name='institution_name_ccaed3_idx'), models.Index(fields=['slug'], name='institution_slug_6f1103_idx')],
            },
        ),
    ]
