# Generated by Django 5.2.8 on 2026-06-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="abbreviation",
            field=models.CharField(
                blank=True, help_text="Short code, e.g. UoN, KU, JKUAT", max_length=20
            ),
        ),
    ]
