# Generated by Django 6.0.6 on 2026-06-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_add_coursespotlight"),
        ("institutions", "0003_institutionpromotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionpromotion",
            name="featured_course",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific course to spotlight in career results (course_spotlight tier only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsorships",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="institutionpromotion",
            name="pathway",
            field=models.CharField(
                choices=[
                    ("all", "All Pathways"),
                    ("Degree", "Degree (University)"),
                    ("Diploma", "Diploma"),
                    ("KMTC", "KMTC"),
                    ("TVET", "TVET"),
                    ("TTC", "TTC"),
                ],
                default="all",
                help_text="Which career pathway to show this sponsored listing in (course_spotlight tier)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institutionpromotion",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="institutions.institution",
            ),
        ),
        migrations.AlterField(
            model_name="institutionpromotion",
            name="tier",
            field=models.CharField(
                choices=[
                    ("featured", "Featured Partner"),
                    ("scholarship", "Scholarship Alert"),
                    ("course_spotlight", "Sponsored Course Listing"),
                ],
                default="featured",
                max_length=20,
            ),
        ),
    ]
