# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_courses_cou_course__320d41_idx_and_more"),
        ("institutions", "0004_institutionpromotion_course_spotlight"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["institution_type"], name="institution_institu_7ec5c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionpromotion",
            index=models.Index(
                fields=["start_date", "end_date"], name="institution_start_d_1000b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionpromotion",
            index=models.Index(fields=["tier"], name="institution_tier_25796b_idx"),
        ),
        migrations.AddIndex(
            model_name="institutionpromotion",
            index=models.Index(
                fields=["pathway"], name="institution_pathway_88119a_idx"
            ),
        ),
    ]
