# Generated by Django 5.2.15 on 2026-09-26 10:50

import kuccpss.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0005_institution_institution_institu_7ec5c7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="institution_logos/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF brochure or requirements",
                null=True,
                upload_to="institution_pdfs/",
                validators=[kuccpss.upload_validators.SafePDFValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="institutionpromotion",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="institution_banners/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
    ]
