# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "institutions",
            "0006_alter_institution_logo_alter_institution_pdf_file_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="institution",
            name="institution_slug_6f1103_idx",
        ),
        migrations.RemoveIndex(
            model_name="institution",
            name="institution_institu_7ec5c7_idx",
        ),
        migrations.RemoveIndex(
            model_name="institutiontype",
            name="institution_name_c8a941_idx",
        ),
        migrations.RemoveIndex(
            model_name="institutiontype",
            name="institution_slug_1b23ad_idx",
        ),
    ]
