# Generated by Django 6.0.6 on 2026-06-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("excerpt", models.CharField(blank=True, max_length=300)),
                ("content", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/thumbnails/"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags, e.g. career,university,tips",
                        max_length=255,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon class", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Resource Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Guide"),
                            ("video", "Video"),
                            ("link", "External Link"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="resources/pdfs/"
                    ),
                ),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="resources/thumbnails/"
                    ),
                ),
                ("is_free", models.BooleanField(default=True)),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="resources.resourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
