# Generated by Django 6.0.6 on 2026-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Pin as the featured headline article"
            ),
        ),
    ]
