# Generated by Django 6.0.6 on 2026-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_add_article_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=400)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("cluster", "Cluster Points"),
                            ("courses", "Courses & Pathways"),
                            ("kuccps", "KUCCPS Process"),
                            ("account", "My Account"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first within each category",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "FAQ Item",
                "verbose_name_plural": "FAQ Items",
                "ordering": ["category", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key used in views/templates",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Human-readable label", max_length=200),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text"),
                            ("textarea", "Long Text"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("phone", "Phone / WhatsApp"),
                            ("number", "Number"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        default="general",
                        help_text="Group name for admin display (e.g. contact, social, hero)",
                        max_length=50,
                    ),
                ),
                (
                    "help_note",
                    models.CharField(
                        blank=True,
                        help_text="Extra hint for the admin editing this value",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
                "ordering": ["group", "key"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "initials",
                    models.CharField(
                        blank=True,
                        help_text="2-letter avatar initials — auto-filled from name if blank",
                        max_length=4,
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        blank=True,
                        help_text="Home county, e.g. Kiambu County",
                        max_length=80,
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True,
                        help_text="City/region where they work now, e.g. Nairobi",
                        max_length=100,
                    ),
                ),
                (
                    "kcse_grade",
                    models.CharField(
                        blank=True, help_text="Mean grade, e.g. A-, C+, B", max_length=4
                    ),
                ),
                (
                    "quote",
                    models.TextField(help_text="Their testimonial in their own words"),
                ),
                ("course_name", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                (
                    "pathway",
                    models.CharField(
                        choices=[
                            ("degree", "Degree"),
                            ("kmtc", "KMTC"),
                            ("tvet", "TVET / Polytechnic"),
                            ("ttc", "TTC"),
                            ("diploma", "Diploma"),
                            ("artisan", "Artisan Certificate"),
                        ],
                        default="degree",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Graduation year", null=True
                    ),
                ),
                (
                    "avatar_bg",
                    models.CharField(
                        default="#eef2ff",
                        help_text="Avatar background colour (hex)",
                        max_length=20,
                    ),
                ),
                (
                    "avatar_color",
                    models.CharField(
                        default="#4f46e5",
                        help_text="Avatar text colour (hex)",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Success Story",
                "verbose_name_plural": "Success Stories",
                "ordering": ["order", "id"],
            },
        ),
    ]
