# Generated by Django 6.0.6 on 2026-06-21 06:21

from django.db import migrations


def seed_admin_email(apps, schema_editor):
    SiteSetting = apps.get_model('resources', 'SiteSetting')
    SiteSetting.objects.get_or_create(
        key='admin_email',
        defaults={
            'label':        'Admin Notification Email',
            'value':        'limomeshk@gmail.com',
            'setting_type': 'email',
            'group':        'contact',
            'help_note':    'All admin alert emails (mentor applications, refunds, withdrawals) are sent here.',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_add_faqitem_successstory_sitesetting"),
    ]

    operations = [
        migrations.RunPython(seed_admin_email, reverse_code=migrations.RunPython.noop),
    ]
