# Generated by Django 6.0.6 on 2026-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_seed_admin_email_setting"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published", "featured"],
                name="resources_a_is_publ_ccd124_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published"], name="resources_a_is_publ_c2c036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(
                fields=["category", "is_active"], name="resources_f_categor_9c4f3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(
                fields=["is_active"], name="resources_f_is_acti_815a2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "is_free"],
                name="resources_r_resourc_045814_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["category"], name="resources_r_categor_499e30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitesetting",
            index=models.Index(fields=["group"], name="resources_s_group_26cf42_idx"),
        ),
        migrations.AddIndex(
            model_name="successstory",
            index=models.Index(
                fields=["is_active", "pathway"], name="resources_s_is_acti_1fd394_idx"
            ),
        ),
    ]
