# Generated by Django 6.0.6 on 2026-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_article_resources_a_is_publ_ccd124_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="Short announcement text shown to users"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional call-to-action URL"
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        blank=True, help_text="Button label for the link", max_length=60
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("info", "Info (blue)"),
                            ("success", "Success (green)"),
                            ("warning", "Warning (yellow)"),
                            ("danger", "Alert (red)"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to show immediately",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to show indefinitely",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="resources_a_is_acti_012c69_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("suggestion", "Feature Suggestion"),
                            ("general", "General Feedback"),
                            ("content", "Content Error"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Optional — for follow-up", max_length=254
                    ),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True,
                        help_text="Page where feedback was submitted",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, help_text="Internal note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Site Feedback",
                "verbose_name_plural": "Site Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="resources_s_status_cc1794_idx"
                    ),
                    models.Index(
                        fields=["feedback_type", "status"],
                        name="resources_s_feedbac_c95e57_idx",
                    ),
                ],
            },
        ),
    ]
