# Generated by Django 5.2.15 on 2026-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_seed_performance_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadlineBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show the countdown bar site-wide"
                    ),
                ),
                (
                    "heading_text",
                    models.CharField(default="⏰ KUCCPS 2026", max_length=100),
                ),
                (
                    "deadline1_label",
                    models.CharField(
                        default="KUCCPS Portal Opens — Build Your Shortlist Now",
                        max_length=150,
                    ),
                ),
                (
                    "deadline1_date",
                    models.DateTimeField(
                        help_text="First key date, e.g. portal opening"
                    ),
                ),
                (
                    "deadline2_label",
                    models.CharField(
                        blank=True, default="KUCCPS Application Closes", max_length=150
                    ),
                ),
                (
                    "deadline2_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Second key date, e.g. application deadline",
                        null=True,
                    ),
                ),
                (
                    "auth_link1_label",
                    models.CharField(default="Check Eligibility →", max_length=60),
                ),
                (
                    "auth_link1_url",
                    models.CharField(
                        default="/career/",
                        help_text="Shown to logged-in users",
                        max_length=300,
                    ),
                ),
                (
                    "auth_link2_label",
                    models.CharField(
                        blank=True, default="Apply on KUCCPS →", max_length=60
                    ),
                ),
                (
                    "auth_link2_url",
                    models.CharField(
                        blank=True,
                        default="https://students.kuccps.net/login/",
                        max_length=300,
                    ),
                ),
                (
                    "guest_link1_label",
                    models.CharField(default="Calculate Points →", max_length=60),
                ),
                (
                    "guest_link1_url",
                    models.CharField(
                        default="/career/",
                        help_text="Shown to logged-out visitors",
                        max_length=300,
                    ),
                ),
                (
                    "guest_link2_label",
                    models.CharField(
                        blank=True, default="Apply on KUCCPS →", max_length=60
                    ),
                ),
                (
                    "guest_link2_url",
                    models.CharField(
                        blank=True,
                        default="https://students.kuccps.net/login/",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deadline Banner",
                "verbose_name_plural": "Deadline Banner",
            },
        ),
    ]
