# Generated by Django 5.2.15 on 2026-09-26 10:50

import kuccpss.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_seed_whatsapp_group_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/thumbnails/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resources/pdfs/",
                validators=[kuccpss.upload_validators.SafePDFValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="resources/thumbnails/",
                validators=[kuccpss.upload_validators.SafeImageValidator()],
            ),
        ),
    ]
