# Generated by Django 5.2.15 on 2026-09-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0012_alter_article_thumbnail_alter_resource_pdf_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "KCSE 2025 Cycle"', max_length=120
                    ),
                ),
                (
                    "tab_label",
                    models.CharField(
                        help_text='Hero tab text, e.g. "KCSE 2025 Cycle (2026)"',
                        max_length=120,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "For students who sat KCSE in October–November 2025"',
                        max_length=250,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight as the current cycle (only one should be ticked)",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text='Show the grey "Completed" badge'
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide this cycle from the page",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
            ],
            options={
                "verbose_name": "KUCCPS Calendar Cycle",
                "verbose_name_plural": "KUCCPS Calendar",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        help_text='Phase heading shown above this event when it changes, e.g. "Phase 3 — Applications". Leave blank for none.',
                        max_length=120,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "date_label",
                    models.CharField(
                        help_text='Date text shown on the card, e.g. "April – May 2026"',
                        max_length=80,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional — used when status is Auto",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional — used when status is Auto",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (from dates)"),
                            ("done", "Done"),
                            ("active", "Open now"),
                            ("expected", "Expected"),
                            ("upcoming", "Upcoming"),
                            ("tba", "TBA"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-calendar",
                        help_text='Font Awesome icon name, e.g. "fa-pen", "fa-globe", "fa-award"',
                        max_length=40,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("amber", "Amber"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                            ("teal", "Teal"),
                            ("gray", "Gray"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="resources.calendarcycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "ordering": ["cycle", "order", "id"],
            },
        ),
    ]
