# Generated by Django 5.2.15 on 2026-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0015_seed_contact_phone_setting"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="resource",
            name="resources_r_categor_499e30_idx",
        ),
    ]
